// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// ==============================================================

extern void AESL_WRAP_Conv (
ap_uint<16> CHin,
ap_uint<16> Hin,
ap_uint<16> Win,
ap_uint<16> CHout,
ap_uint<8> Kx,
ap_uint<8> Ky,
ap_uint<8> Sx,
ap_uint<8> Sy,
ap_uint<1> mode,
ap_uint<1> relu_en,
ap_int<128>* feature_in,
ap_uint<4> feature_in_precision,
ap_int<128>* W,
ap_uint<4> W_precision,
ap_int<128>* feature_out,
ap_uint<4> feature_out_precision);
