// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module pool_2D (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        in_V_V_dout,
        in_V_V_empty_n,
        in_V_V_read,
        out_V_V_din,
        out_V_V_full_n,
        out_V_V_write,
        ch_div_K,
        height_in,
        width_out,
        Ky
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_pp0_stage0 = 5'd2;
parameter    ap_ST_fsm_pp0_stage1 = 5'd4;
parameter    ap_ST_fsm_pp0_stage2 = 5'd8;
parameter    ap_ST_fsm_state42 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [127:0] in_V_V_dout;
input   in_V_V_empty_n;
output   in_V_V_read;
output  [127:0] out_V_V_din;
input   out_V_V_full_n;
output   out_V_V_write;
input  [31:0] ch_div_K;
input  [31:0] height_in;
input  [31:0] width_out;
input  [31:0] Ky;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg in_V_V_read;
reg out_V_V_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    in_V_V_blk_n;
wire    ap_CS_fsm_pp0_stage2;
reg    ap_enable_reg_pp0_iter11;
wire    ap_block_pp0_stage2;
reg   [0:0] exitcond_flatten1_reg_2038;
reg   [0:0] exitcond_flatten1_reg_2038_pp0_iter11_reg;
reg    out_V_V_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter13;
wire    ap_block_pp0_stage0;
reg   [0:0] tmp_9_reg_2079;
reg   [95:0] indvar_flatten1_reg_203;
reg   [63:0] indvar_flatten_reg_214;
reg   [30:0] i_reg_225;
reg  signed [31:0] ptr_tp_reg_236;
reg   [31:0] j_reg_248;
reg    ap_block_state1;
wire   [31:0] tmp_fu_329_p2;
wire   [0:0] sel_tmp_fu_335_p2;
wire   [0:0] sel_tmp2_fu_341_p2;
wire   [0:0] sel_tmp4_fu_347_p2;
wire   [0:0] sel_tmp6_fu_353_p2;
wire   [63:0] bound_fu_367_p2;
wire   [95:0] bound4_fu_381_p2;
wire   [0:0] tmp_5_mid_fu_387_p2;
wire   [0:0] exitcond_flatten1_fu_399_p2;
wire    ap_block_state2_pp0_stage0_iter0;
wire    ap_block_state5_pp0_stage0_iter1;
wire    ap_block_state8_pp0_stage0_iter2;
wire    ap_block_state11_pp0_stage0_iter3;
wire    ap_block_state14_pp0_stage0_iter4;
wire    ap_block_state17_pp0_stage0_iter5;
wire    ap_block_state20_pp0_stage0_iter6;
wire    ap_block_state23_pp0_stage0_iter7;
wire    ap_block_state26_pp0_stage0_iter8;
wire    ap_block_state29_pp0_stage0_iter9;
wire    ap_block_state32_pp0_stage0_iter10;
wire    ap_block_state35_pp0_stage0_iter11;
wire    ap_block_state38_pp0_stage0_iter12;
reg    ap_block_state41_pp0_stage0_iter13;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] exitcond_flatten1_reg_2038_pp0_iter1_reg;
reg   [0:0] exitcond_flatten1_reg_2038_pp0_iter2_reg;
reg   [0:0] exitcond_flatten1_reg_2038_pp0_iter3_reg;
reg   [0:0] exitcond_flatten1_reg_2038_pp0_iter4_reg;
reg   [0:0] exitcond_flatten1_reg_2038_pp0_iter5_reg;
reg   [0:0] exitcond_flatten1_reg_2038_pp0_iter6_reg;
reg   [0:0] exitcond_flatten1_reg_2038_pp0_iter7_reg;
reg   [0:0] exitcond_flatten1_reg_2038_pp0_iter8_reg;
reg   [0:0] exitcond_flatten1_reg_2038_pp0_iter9_reg;
reg   [0:0] exitcond_flatten1_reg_2038_pp0_iter10_reg;
reg   [0:0] exitcond_flatten1_reg_2038_pp0_iter12_reg;
wire   [95:0] indvar_flatten_next1_fu_404_p2;
reg   [95:0] indvar_flatten_next1_reg_2042;
reg    ap_enable_reg_pp0_iter0;
wire   [30:0] i_mid2_fu_467_p3;
reg   [30:0] i_mid2_reg_2052;
wire   [31:0] j_1_fu_494_p3;
reg   [31:0] j_1_reg_2057;
wire   [63:0] indvar_flatten_next_fu_508_p3;
reg   [63:0] indvar_flatten_next_reg_2062;
reg   [127:0] in_d0_V_reg_2067;
wire    ap_block_state4_pp0_stage2_iter0;
wire    ap_block_state7_pp0_stage2_iter1;
wire    ap_block_state10_pp0_stage2_iter2;
wire    ap_block_state13_pp0_stage2_iter3;
wire    ap_block_state16_pp0_stage2_iter4;
wire    ap_block_state19_pp0_stage2_iter5;
wire    ap_block_state22_pp0_stage2_iter6;
wire    ap_block_state25_pp0_stage2_iter7;
wire    ap_block_state28_pp0_stage2_iter8;
wire    ap_block_state31_pp0_stage2_iter9;
wire    ap_block_state34_pp0_stage2_iter10;
reg    ap_block_state37_pp0_stage2_iter11;
wire    ap_block_state40_pp0_stage2_iter12;
reg    ap_block_pp0_stage2_11001;
wire   [0:0] tmp_9_fu_521_p2;
wire   [31:0] ptr_tp_2_fu_598_p3;
reg   [31:0] ptr_tp_2_reg_2093;
wire   [31:0] ptr_1_fu_618_p3;
reg   [31:0] ptr_1_reg_2098;
reg    ap_enable_reg_pp0_iter12;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_state3_pp0_stage1_iter0;
wire    ap_block_state6_pp0_stage1_iter1;
wire    ap_block_state9_pp0_stage1_iter2;
wire    ap_block_state12_pp0_stage1_iter3;
wire    ap_block_state15_pp0_stage1_iter4;
wire    ap_block_state18_pp0_stage1_iter5;
wire    ap_block_state21_pp0_stage1_iter6;
wire    ap_block_state24_pp0_stage1_iter7;
wire    ap_block_state27_pp0_stage1_iter8;
wire    ap_block_state30_pp0_stage1_iter9;
wire    ap_block_state33_pp0_stage1_iter10;
wire    ap_block_state36_pp0_stage1_iter11;
wire    ap_block_state39_pp0_stage1_iter12;
wire    ap_block_pp0_stage1_11001;
wire   [15:0] tmp_22_fu_630_p1;
reg   [15:0] tmp_22_reg_2108;
wire   [15:0] tmp_23_fu_634_p1;
reg   [15:0] tmp_23_reg_2118;
wire   [15:0] grp_fu_259_p4;
reg   [15:0] p_Result_1_1_reg_2126;
reg   [15:0] p_Result_2_1_reg_2136;
wire   [15:0] grp_fu_269_p4;
reg   [15:0] p_Result_1_2_reg_2144;
reg   [15:0] p_Result_2_2_reg_2154;
wire   [15:0] grp_fu_279_p4;
reg   [15:0] p_Result_1_3_reg_2162;
reg   [15:0] p_Result_2_3_reg_2172;
reg   [15:0] p_Result_1_4_reg_2180;
reg   [15:0] p_Result_2_4_reg_2190;
reg   [15:0] p_Result_1_5_reg_2198;
reg   [15:0] p_Result_2_5_reg_2208;
reg   [15:0] p_Result_1_6_reg_2216;
reg   [15:0] p_Result_2_6_reg_2226;
reg   [15:0] p_Result_1_7_reg_2234;
reg   [15:0] p_Result_2_7_reg_2244;
wire   [127:0] p_0219_4_3_fu_1338_p3;
reg   [127:0] p_0219_4_3_reg_2252;
reg   [15:0] p_Result_1_reg_2261;
reg   [15:0] p_Result_3_4_reg_2272;
reg   [15:0] p_Result_2_reg_2278;
reg   [15:0] p_Result_3_5_reg_2289;
reg   [15:0] p_Result_3_reg_2295;
reg   [15:0] p_Result_3_6_reg_2306;
reg   [15:0] p_Result_10_reg_2312;
reg   [15:0] p_Result_3_7_reg_2323;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state2;
reg    ap_enable_reg_pp0_iter1;
reg    ap_block_pp0_stage2_subdone;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg   [6:0] buf_V_address0;
reg    buf_V_ce0;
wire   [127:0] buf_V_q0;
reg   [6:0] buf_V_address1;
reg    buf_V_ce1;
reg    buf_V_we1;
wire   [127:0] buf_V_q1;
reg   [95:0] ap_phi_mux_indvar_flatten1_phi_fu_207_p4;
reg   [63:0] ap_phi_mux_indvar_flatten_phi_fu_218_p4;
reg   [30:0] ap_phi_mux_i_phi_fu_229_p4;
reg  signed [31:0] ap_phi_mux_ptr_tp_phi_fu_240_p4;
reg   [31:0] ap_phi_mux_j_phi_fu_252_p4;
wire  signed [63:0] tmp_6_fu_516_p1;
wire  signed [63:0] tmp_3_fu_550_p1;
wire  signed [63:0] tmp_7_fu_578_p1;
wire  signed [63:0] tmp_10_fu_626_p1;
wire    ap_block_pp0_stage1;
wire   [127:0] tmp_V_2_fu_1933_p3;
reg    ap_block_pp0_stage0_01001;
reg   [127:0] tmp_V_fu_122;
wire   [31:0] bound_fu_367_p0;
wire   [31:0] bound_fu_367_p1;
wire   [63:0] bound4_fu_381_p0;
wire   [31:0] bound4_fu_381_p1;
wire   [0:0] exitcond_flatten_fu_410_p2;
wire   [30:0] i_1_fu_393_p2;
wire   [0:0] tmp_5_fu_431_p2;
wire   [30:0] i_mid_fu_415_p3;
wire   [0:0] tmp_5_mid1_fu_436_p3;
wire   [30:0] i_1_cast_mid_fu_423_p3;
wire   [30:0] i_1_mid1_fu_449_p2;
wire   [30:0] i_1_cast_mid2_fu_455_p3;
wire   [30:0] i_1_dup_fu_443_p2;
wire   [32:0] grp_fu_475_p0;
wire   [31:0] j_op_fu_480_p2;
wire   [31:0] j_mid212_op_fu_486_p3;
wire   [63:0] indvar_flatten_op_fu_502_p2;
wire   [31:0] grp_fu_475_p2;
wire   [0:0] tmp_s_fu_527_p2;
wire   [31:0] ptr_tp_3_fu_532_p2;
wire   [31:0] ptr_tp_4_fu_537_p2;
wire  signed [31:0] ptr_tp_5_fu_542_p3;
wire   [0:0] tmp_4_fu_555_p2;
wire   [31:0] ptr_tp_6_fu_560_p2;
wire   [31:0] ptr_tp_7_fu_565_p2;
wire  signed [31:0] ptr_tp_1_fu_570_p3;
wire   [0:0] tmp_2_fu_583_p2;
wire   [31:0] ptr_tp_8_fu_588_p2;
wire   [31:0] ptr_tp_9_fu_593_p2;
wire   [0:0] tmp_12_fu_606_p2;
wire   [31:0] ptr_fu_612_p2;
wire   [15:0] tmp_21_fu_711_p1;
wire   [0:0] tmp_11_fu_730_p2;
wire   [15:0] tmp_13_fu_735_p3;
wire   [0:0] tmp_14_fu_754_p2;
wire   [15:0] tmp_15_fu_758_p3;
wire   [0:0] tmp_16_fu_764_p2;
wire   [15:0] tp_d0_V_1_fu_770_p3;
wire   [15:0] tmp_24_fu_714_p1;
wire   [0:0] tmp_17_fu_790_p2;
wire   [15:0] tmp_18_fu_795_p3;
wire   [0:0] tmp_19_fu_802_p2;
wire   [15:0] tp_d1_V_1_fu_807_p3;
wire   [0:0] tmp_20_fu_814_p2;
wire   [15:0] p_in347_ld_fu_820_p3;
wire   [127:0] p_Result_7_fu_828_p5;
wire   [127:0] p_Result_6_fu_778_p5;
wire   [127:0] sel_tmp1_fu_840_p3;
wire   [127:0] p_Result_5_fu_742_p5;
wire   [127:0] sel_tmp3_fu_847_p3;
wire   [127:0] p_Result_4_fu_718_p5;
wire   [127:0] sel_tmp5_fu_854_p3;
wire   [127:0] p_0219_4_fu_861_p3;
wire   [15:0] p_Result_s_fu_868_p4;
wire   [0:0] tmp_13_1_fu_889_p2;
wire   [15:0] tmp_14_1_fu_894_p3;
wire   [0:0] tmp_15_1_fu_913_p2;
wire   [15:0] tmp_16_1_fu_917_p3;
wire   [0:0] tmp_17_1_fu_923_p2;
wire   [15:0] tp_d0_V_1_1_fu_929_p3;
wire   [0:0] tmp_18_1_fu_949_p2;
wire   [15:0] tmp_19_1_fu_954_p3;
wire   [0:0] tmp_20_1_fu_961_p2;
wire   [15:0] tp_d1_V_1_1_fu_966_p3;
wire   [0:0] tmp_21_1_fu_973_p2;
wire   [15:0] p_in347_ld_1_fu_979_p3;
wire   [127:0] p_Result_7_1_fu_987_p5;
wire   [127:0] p_Result_6_1_fu_937_p5;
wire   [127:0] sel_tmp9_fu_999_p3;
wire   [127:0] p_Result_5_1_fu_901_p5;
wire   [127:0] sel_tmp7_fu_1006_p3;
wire   [127:0] p_Result_4_1_fu_877_p5;
wire   [127:0] sel_tmp8_fu_1013_p3;
wire   [127:0] p_0219_4_1_fu_1020_p3;
wire   [15:0] p_Result_8_fu_1027_p4;
wire   [0:0] tmp_13_2_fu_1048_p2;
wire   [15:0] tmp_14_2_fu_1053_p3;
wire   [0:0] tmp_15_2_fu_1072_p2;
wire   [15:0] tmp_16_2_fu_1076_p3;
wire   [0:0] tmp_17_2_fu_1082_p2;
wire   [15:0] tp_d0_V_1_2_fu_1088_p3;
wire   [0:0] tmp_18_2_fu_1108_p2;
wire   [15:0] tmp_19_2_fu_1113_p3;
wire   [0:0] tmp_20_2_fu_1120_p2;
wire   [15:0] tp_d1_V_1_2_fu_1125_p3;
wire   [0:0] tmp_21_2_fu_1132_p2;
wire   [15:0] p_in347_ld_2_fu_1138_p3;
wire   [127:0] p_Result_7_2_fu_1146_p5;
wire   [127:0] p_Result_6_2_fu_1096_p5;
wire   [127:0] sel_tmp10_fu_1158_p3;
wire   [127:0] p_Result_5_2_fu_1060_p5;
wire   [127:0] sel_tmp11_fu_1165_p3;
wire   [127:0] p_Result_4_2_fu_1036_p5;
wire   [127:0] sel_tmp12_fu_1172_p3;
wire   [127:0] p_0219_4_2_fu_1179_p3;
wire   [15:0] p_Result_9_fu_1186_p4;
wire   [0:0] tmp_13_3_fu_1207_p2;
wire   [15:0] tmp_14_3_fu_1212_p3;
wire   [0:0] tmp_15_3_fu_1231_p2;
wire   [15:0] tmp_16_3_fu_1235_p3;
wire   [0:0] tmp_17_3_fu_1241_p2;
wire   [15:0] tp_d0_V_1_3_fu_1247_p3;
wire   [0:0] tmp_18_3_fu_1267_p2;
wire   [15:0] tmp_19_3_fu_1272_p3;
wire   [0:0] tmp_20_3_fu_1279_p2;
wire   [15:0] tp_d1_V_1_3_fu_1284_p3;
wire   [0:0] tmp_21_3_fu_1291_p2;
wire   [15:0] p_in347_ld_3_fu_1297_p3;
wire   [127:0] p_Result_7_3_fu_1305_p5;
wire   [127:0] p_Result_6_3_fu_1255_p5;
wire   [127:0] sel_tmp13_fu_1317_p3;
wire   [127:0] p_Result_5_3_fu_1219_p5;
wire   [127:0] sel_tmp14_fu_1324_p3;
wire   [127:0] p_Result_4_3_fu_1195_p5;
wire   [127:0] sel_tmp15_fu_1331_p3;
wire   [0:0] tmp_13_4_fu_1391_p2;
wire   [15:0] tmp_14_4_fu_1395_p3;
wire   [0:0] tmp_15_4_fu_1412_p2;
wire   [15:0] tmp_16_4_fu_1416_p3;
wire   [0:0] tmp_17_4_fu_1422_p2;
wire   [15:0] tp_d0_V_1_4_fu_1427_p3;
wire   [0:0] tmp_18_4_fu_1445_p2;
wire   [15:0] tmp_19_4_fu_1449_p3;
wire   [0:0] tmp_20_4_fu_1455_p2;
wire   [15:0] tp_d1_V_1_4_fu_1460_p3;
wire   [0:0] tmp_21_4_fu_1467_p2;
wire   [15:0] p_in347_ld_4_fu_1472_p3;
wire   [127:0] p_Result_7_4_fu_1479_p5;
wire   [127:0] p_Result_6_4_fu_1434_p5;
wire   [127:0] sel_tmp16_fu_1490_p3;
wire   [127:0] p_Result_5_4_fu_1401_p5;
wire   [127:0] sel_tmp17_fu_1496_p3;
wire   [127:0] p_Result_4_4_fu_1381_p5;
wire   [127:0] sel_tmp18_fu_1503_p3;
wire   [127:0] p_0219_4_4_fu_1510_p3;
wire   [0:0] tmp_13_5_fu_1528_p2;
wire   [15:0] tmp_14_5_fu_1532_p3;
wire   [0:0] tmp_15_5_fu_1550_p2;
wire   [15:0] tmp_16_5_fu_1554_p3;
wire   [0:0] tmp_17_5_fu_1560_p2;
wire   [15:0] tp_d0_V_1_5_fu_1565_p3;
wire   [0:0] tmp_18_5_fu_1584_p2;
wire   [15:0] tmp_19_5_fu_1588_p3;
wire   [0:0] tmp_20_5_fu_1594_p2;
wire   [15:0] tp_d1_V_1_5_fu_1599_p3;
wire   [0:0] tmp_21_5_fu_1606_p2;
wire   [15:0] p_in347_ld_5_fu_1611_p3;
wire   [127:0] p_Result_7_5_fu_1618_p5;
wire   [127:0] p_Result_6_5_fu_1572_p5;
wire   [127:0] sel_tmp19_fu_1630_p3;
wire   [127:0] p_Result_5_5_fu_1538_p5;
wire   [127:0] sel_tmp20_fu_1637_p3;
wire   [127:0] p_Result_4_5_fu_1517_p5;
wire   [127:0] sel_tmp21_fu_1644_p3;
wire   [127:0] p_0219_4_5_fu_1651_p3;
wire   [0:0] tmp_13_6_fu_1669_p2;
wire   [15:0] tmp_14_6_fu_1673_p3;
wire   [0:0] tmp_15_6_fu_1691_p2;
wire   [15:0] tmp_16_6_fu_1695_p3;
wire   [0:0] tmp_17_6_fu_1701_p2;
wire   [15:0] tp_d0_V_1_6_fu_1706_p3;
wire   [0:0] tmp_18_6_fu_1725_p2;
wire   [15:0] tmp_19_6_fu_1729_p3;
wire   [0:0] tmp_20_6_fu_1735_p2;
wire   [15:0] tp_d1_V_1_6_fu_1740_p3;
wire   [0:0] tmp_21_6_fu_1747_p2;
wire   [15:0] p_in347_ld_6_fu_1752_p3;
wire   [127:0] p_Result_7_6_fu_1759_p5;
wire   [127:0] p_Result_6_6_fu_1713_p5;
wire   [127:0] sel_tmp22_fu_1771_p3;
wire   [127:0] p_Result_5_6_fu_1679_p5;
wire   [127:0] sel_tmp23_fu_1778_p3;
wire   [127:0] p_Result_4_6_fu_1658_p5;
wire   [127:0] sel_tmp24_fu_1785_p3;
wire   [127:0] p_0219_4_6_fu_1792_p3;
wire   [0:0] tmp_13_7_fu_1810_p2;
wire   [15:0] tmp_14_7_fu_1814_p3;
wire   [0:0] tmp_15_7_fu_1832_p2;
wire   [15:0] tmp_16_7_fu_1836_p3;
wire   [0:0] tmp_17_7_fu_1842_p2;
wire   [15:0] tp_d0_V_1_7_fu_1847_p3;
wire   [0:0] tmp_18_7_fu_1866_p2;
wire   [15:0] tmp_19_7_fu_1870_p3;
wire   [0:0] tmp_20_7_fu_1876_p2;
wire   [15:0] tp_d1_V_1_7_fu_1881_p3;
wire   [0:0] tmp_21_7_fu_1888_p2;
wire   [15:0] p_in347_ld_7_fu_1893_p3;
wire   [127:0] p_Result_7_7_fu_1900_p5;
wire   [127:0] p_Result_6_7_fu_1854_p5;
wire   [127:0] sel_tmp25_fu_1912_p3;
wire   [127:0] p_Result_5_7_fu_1820_p5;
wire   [127:0] sel_tmp26_fu_1919_p3;
wire   [127:0] p_Result_4_7_fu_1799_p5;
wire   [127:0] sel_tmp27_fu_1926_p3;
reg    grp_fu_475_ce;
wire    ap_CS_fsm_state42;
reg   [4:0] ap_NS_fsm;
wire    ap_block_pp0_stage1_subdone;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire   [95:0] bound4_fu_381_p00;
wire   [95:0] bound4_fu_381_p10;
wire   [63:0] bound_fu_367_p00;
wire   [63:0] bound_fu_367_p10;
wire   [31:0] grp_fu_475_p00;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 5'd1;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
end

pool_2D_buf_V #(
    .DataWidth( 128 ),
    .AddressRange( 128 ),
    .AddressWidth( 7 ))
buf_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(buf_V_address0),
    .ce0(buf_V_ce0),
    .q0(buf_V_q0),
    .address1(buf_V_address1),
    .ce1(buf_V_ce1),
    .we1(buf_V_we1),
    .d1(in_V_V_dout),
    .q1(buf_V_q1)
);

pool_srem_33ns_32bkb #(
    .ID( 1 ),
    .NUM_STAGE( 37 ),
    .din0_WIDTH( 33 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
pool_srem_33ns_32bkb_U9(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_475_p0),
    .din1(Ky),
    .ce(grp_fu_475_ce),
    .dout(grp_fu_475_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state42)) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_condition_pp0_exit_iter0_state2))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            if ((1'b1 == ap_condition_pp0_exit_iter0_state2)) begin
                ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state2);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2)))) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end else if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter13 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_flatten1_reg_2038 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        i_reg_225 <= i_mid2_reg_2052;
    end else if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        i_reg_225 <= 31'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_flatten1_reg_2038 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        indvar_flatten1_reg_203 <= indvar_flatten_next1_reg_2042;
    end else if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        indvar_flatten1_reg_203 <= 96'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_flatten1_reg_2038 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        indvar_flatten_reg_214 <= indvar_flatten_next_reg_2062;
    end else if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        indvar_flatten_reg_214 <= 64'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_flatten1_reg_2038 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        j_reg_248 <= j_1_reg_2057;
    end else if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        j_reg_248 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_flatten1_reg_2038_pp0_iter12_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001))) begin
        ptr_tp_reg_236 <= ptr_1_reg_2098;
    end else if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ptr_tp_reg_236 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        exitcond_flatten1_reg_2038 <= exitcond_flatten1_fu_399_p2;
        exitcond_flatten1_reg_2038_pp0_iter10_reg <= exitcond_flatten1_reg_2038_pp0_iter9_reg;
        exitcond_flatten1_reg_2038_pp0_iter11_reg <= exitcond_flatten1_reg_2038_pp0_iter10_reg;
        exitcond_flatten1_reg_2038_pp0_iter12_reg <= exitcond_flatten1_reg_2038_pp0_iter11_reg;
        exitcond_flatten1_reg_2038_pp0_iter1_reg <= exitcond_flatten1_reg_2038;
        exitcond_flatten1_reg_2038_pp0_iter2_reg <= exitcond_flatten1_reg_2038_pp0_iter1_reg;
        exitcond_flatten1_reg_2038_pp0_iter3_reg <= exitcond_flatten1_reg_2038_pp0_iter2_reg;
        exitcond_flatten1_reg_2038_pp0_iter4_reg <= exitcond_flatten1_reg_2038_pp0_iter3_reg;
        exitcond_flatten1_reg_2038_pp0_iter5_reg <= exitcond_flatten1_reg_2038_pp0_iter4_reg;
        exitcond_flatten1_reg_2038_pp0_iter6_reg <= exitcond_flatten1_reg_2038_pp0_iter5_reg;
        exitcond_flatten1_reg_2038_pp0_iter7_reg <= exitcond_flatten1_reg_2038_pp0_iter6_reg;
        exitcond_flatten1_reg_2038_pp0_iter8_reg <= exitcond_flatten1_reg_2038_pp0_iter7_reg;
        exitcond_flatten1_reg_2038_pp0_iter9_reg <= exitcond_flatten1_reg_2038_pp0_iter8_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_flatten1_fu_399_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        i_mid2_reg_2052 <= i_mid2_fu_467_p3;
        indvar_flatten_next_reg_2062 <= indvar_flatten_next_fu_508_p3;
        j_1_reg_2057 <= j_1_fu_494_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_flatten1_reg_2038_pp0_iter11_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001))) begin
        in_d0_V_reg_2067 <= in_V_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        indvar_flatten_next1_reg_2042 <= indvar_flatten_next1_fu_404_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_9_reg_2079 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001))) begin
        p_0219_4_3_reg_2252 <= p_0219_4_3_fu_1338_p3;
        p_Result_10_reg_2312 <= {{in_d0_V_reg_2067[127:112]}};
        p_Result_1_reg_2261 <= {{in_d0_V_reg_2067[79:64]}};
        p_Result_2_reg_2278 <= {{in_d0_V_reg_2067[95:80]}};
        p_Result_3_reg_2295 <= {{in_d0_V_reg_2067[111:96]}};
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_9_reg_2079 == 1'd1) & (sel_tmp6_fu_353_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter12 == 1'b1))) begin
        p_Result_1_1_reg_2126 <= {{buf_V_q0[31:16]}};
        p_Result_1_2_reg_2144 <= {{buf_V_q0[47:32]}};
        p_Result_1_3_reg_2162 <= {{buf_V_q0[63:48]}};
        p_Result_1_4_reg_2180 <= {{buf_V_q0[79:64]}};
        p_Result_1_5_reg_2198 <= {{buf_V_q0[95:80]}};
        p_Result_1_6_reg_2216 <= {{buf_V_q0[111:96]}};
        p_Result_1_7_reg_2234 <= {{buf_V_q0[127:112]}};
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_9_reg_2079 == 1'd1) & (sel_tmp6_fu_353_p2 == 1'd0) & (sel_tmp4_fu_347_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_Result_2_1_reg_2136 <= {{buf_V_q1[31:16]}};
        p_Result_2_2_reg_2154 <= {{buf_V_q1[47:32]}};
        p_Result_2_3_reg_2172 <= {{buf_V_q1[63:48]}};
        p_Result_2_4_reg_2190 <= {{buf_V_q1[79:64]}};
        p_Result_2_5_reg_2208 <= {{buf_V_q1[95:80]}};
        p_Result_2_6_reg_2226 <= {{buf_V_q1[111:96]}};
        p_Result_2_7_reg_2244 <= {{buf_V_q1[127:112]}};
        tmp_23_reg_2118 <= tmp_23_fu_634_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((sel_tmp_fu_335_p2 == 1'd1) & (tmp_9_reg_2079 == 1'd1) & (sel_tmp2_fu_341_p2 == 1'd0) & (sel_tmp6_fu_353_p2 == 1'd0) & (sel_tmp4_fu_347_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001))) begin
        p_Result_3_4_reg_2272 <= {{buf_V_q0[79:64]}};
        p_Result_3_5_reg_2289 <= {{buf_V_q0[95:80]}};
        p_Result_3_6_reg_2306 <= {{buf_V_q0[111:96]}};
        p_Result_3_7_reg_2323 <= {{buf_V_q0[127:112]}};
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_flatten1_reg_2038_pp0_iter11_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ptr_1_reg_2098 <= ptr_1_fu_618_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_9_fu_521_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ptr_tp_2_reg_2093 <= ptr_tp_2_fu_598_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_9_reg_2079 == 1'd1) & (sel_tmp6_fu_353_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        tmp_22_reg_2108 <= tmp_22_fu_630_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_flatten1_reg_2038_pp0_iter11_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_9_reg_2079 <= tmp_9_fu_521_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_9_reg_2079 == 1'd1) & (ap_enable_reg_pp0_iter13 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_V_fu_122 <= tmp_V_2_fu_1933_p3;
    end
end

always @ (*) begin
    if ((exitcond_flatten1_fu_399_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state2 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state2 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state42)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (exitcond_flatten1_reg_2038 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        ap_phi_mux_i_phi_fu_229_p4 = i_mid2_reg_2052;
    end else begin
        ap_phi_mux_i_phi_fu_229_p4 = i_reg_225;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (exitcond_flatten1_reg_2038 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        ap_phi_mux_indvar_flatten1_phi_fu_207_p4 = indvar_flatten_next1_reg_2042;
    end else begin
        ap_phi_mux_indvar_flatten1_phi_fu_207_p4 = indvar_flatten1_reg_203;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (exitcond_flatten1_reg_2038 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        ap_phi_mux_indvar_flatten_phi_fu_218_p4 = indvar_flatten_next_reg_2062;
    end else begin
        ap_phi_mux_indvar_flatten_phi_fu_218_p4 = indvar_flatten_reg_214;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (exitcond_flatten1_reg_2038 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        ap_phi_mux_j_phi_fu_252_p4 = j_1_reg_2057;
    end else begin
        ap_phi_mux_j_phi_fu_252_p4 = j_reg_248;
    end
end

always @ (*) begin
    if (((exitcond_flatten1_reg_2038_pp0_iter12_reg == 1'd0) & (1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter12 == 1'b1))) begin
        ap_phi_mux_ptr_tp_phi_fu_240_p4 = ptr_1_reg_2098;
    end else begin
        ap_phi_mux_ptr_tp_phi_fu_240_p4 = ptr_tp_reg_236;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state42)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter12 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            buf_V_address0 = tmp_10_fu_626_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            buf_V_address0 = tmp_3_fu_550_p1;
        end else begin
            buf_V_address0 = 'bx;
        end
    end else begin
        buf_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter12 == 1'b1))) begin
        buf_V_address1 = tmp_7_fu_578_p1;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter11 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        buf_V_address1 = tmp_6_fu_516_p1;
    end else begin
        buf_V_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter12 == 1'b1)))) begin
        buf_V_ce0 = 1'b1;
    end else begin
        buf_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001)))) begin
        buf_V_ce1 = 1'b1;
    end else begin
        buf_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond_flatten1_reg_2038_pp0_iter11_reg == 1'd0) & (ap_enable_reg_pp0_iter11 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001))) begin
        buf_V_we1 = 1'b1;
    end else begin
        buf_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001)) | ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        grp_fu_475_ce = 1'b1;
    end else begin
        grp_fu_475_ce = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond_flatten1_reg_2038_pp0_iter11_reg == 1'd0) & (1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter11 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        in_V_V_blk_n = in_V_V_empty_n;
    end else begin
        in_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((exitcond_flatten1_reg_2038_pp0_iter11_reg == 1'd0) & (ap_enable_reg_pp0_iter11 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001))) begin
        in_V_V_read = 1'b1;
    end else begin
        in_V_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_9_reg_2079 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter13 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_V_V_blk_n = out_V_V_full_n;
    end else begin
        out_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((tmp_9_reg_2079 == 1'd1) & (ap_enable_reg_pp0_iter13 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        out_V_V_write = 1'b1;
    end else begin
        out_V_V_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((exitcond_flatten1_fu_399_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1)) & ~((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else if ((((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((exitcond_flatten1_fu_399_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_state42;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_state42 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state42 = ap_CS_fsm[32'd4];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((tmp_9_reg_2079 == 1'd1) & (out_V_V_full_n == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((tmp_9_reg_2079 == 1'd1) & (out_V_V_full_n == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((tmp_9_reg_2079 == 1'd1) & (out_V_V_full_n == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b1));
end

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage2_11001 = ((exitcond_flatten1_reg_2038_pp0_iter11_reg == 1'd0) & (in_V_V_empty_n == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage2_subdone = ((exitcond_flatten1_reg_2038_pp0_iter11_reg == 1'd0) & (in_V_V_empty_n == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b1));
end

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_block_state10_pp0_stage2_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage1_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage2_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage1_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage2_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage1_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp0_stage2_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state20_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state21_pp0_stage1_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state22_pp0_stage2_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state23_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state24_pp0_stage1_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state25_pp0_stage2_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state26_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_block_state27_pp0_stage1_iter8 = ~(1'b1 == 1'b1);

assign ap_block_state28_pp0_stage2_iter8 = ~(1'b1 == 1'b1);

assign ap_block_state29_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state30_pp0_stage1_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state31_pp0_stage2_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state32_pp0_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state33_pp0_stage1_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state34_pp0_stage2_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state35_pp0_stage0_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state36_pp0_stage1_iter11 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state37_pp0_stage2_iter11 = ((exitcond_flatten1_reg_2038_pp0_iter11_reg == 1'd0) & (in_V_V_empty_n == 1'b0));
end

assign ap_block_state38_pp0_stage0_iter12 = ~(1'b1 == 1'b1);

assign ap_block_state39_pp0_stage1_iter12 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state40_pp0_stage2_iter12 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state41_pp0_stage0_iter13 = ((tmp_9_reg_2079 == 1'd1) & (out_V_V_full_n == 1'b0));
end

assign ap_block_state4_pp0_stage2_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage1_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage2_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage1_iter2 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign bound4_fu_381_p0 = bound4_fu_381_p00;

assign bound4_fu_381_p00 = bound_fu_367_p2;

assign bound4_fu_381_p1 = bound4_fu_381_p10;

assign bound4_fu_381_p10 = ch_div_K;

assign bound4_fu_381_p2 = (bound4_fu_381_p0 * bound4_fu_381_p1);

assign bound_fu_367_p0 = bound_fu_367_p00;

assign bound_fu_367_p00 = width_out;

assign bound_fu_367_p1 = bound_fu_367_p10;

assign bound_fu_367_p10 = height_in;

assign bound_fu_367_p2 = (bound_fu_367_p0 * bound_fu_367_p1);

assign exitcond_flatten1_fu_399_p2 = ((ap_phi_mux_indvar_flatten1_phi_fu_207_p4 == bound4_fu_381_p2) ? 1'b1 : 1'b0);

assign exitcond_flatten_fu_410_p2 = ((ap_phi_mux_indvar_flatten_phi_fu_218_p4 == bound_fu_367_p2) ? 1'b1 : 1'b0);

assign grp_fu_259_p4 = {{buf_V_q0[31:16]}};

assign grp_fu_269_p4 = {{buf_V_q0[47:32]}};

assign grp_fu_279_p4 = {{buf_V_q0[63:48]}};

assign grp_fu_475_p0 = grp_fu_475_p00;

assign grp_fu_475_p00 = i_1_cast_mid2_fu_455_p3;

assign i_1_cast_mid2_fu_455_p3 = ((tmp_5_mid1_fu_436_p3[0:0] === 1'b1) ? i_1_cast_mid_fu_423_p3 : i_1_mid1_fu_449_p2);

assign i_1_cast_mid_fu_423_p3 = ((exitcond_flatten_fu_410_p2[0:0] === 1'b1) ? 31'd1 : i_1_fu_393_p2);

assign i_1_dup_fu_443_p2 = (i_mid_fu_415_p3 + 31'd1);

assign i_1_fu_393_p2 = (ap_phi_mux_i_phi_fu_229_p4 + 31'd1);

assign i_1_mid1_fu_449_p2 = (i_mid_fu_415_p3 + 31'd2);

assign i_mid2_fu_467_p3 = ((tmp_5_mid1_fu_436_p3[0:0] === 1'b1) ? i_mid_fu_415_p3 : i_1_dup_fu_443_p2);

assign i_mid_fu_415_p3 = ((exitcond_flatten_fu_410_p2[0:0] === 1'b1) ? 31'd0 : ap_phi_mux_i_phi_fu_229_p4);

assign indvar_flatten_next1_fu_404_p2 = (ap_phi_mux_indvar_flatten1_phi_fu_207_p4 + 96'd1);

assign indvar_flatten_next_fu_508_p3 = ((exitcond_flatten_fu_410_p2[0:0] === 1'b1) ? 64'd1 : indvar_flatten_op_fu_502_p2);

assign indvar_flatten_op_fu_502_p2 = (ap_phi_mux_indvar_flatten_phi_fu_218_p4 + 64'd1);

assign j_1_fu_494_p3 = ((tmp_5_mid1_fu_436_p3[0:0] === 1'b1) ? j_mid212_op_fu_486_p3 : 32'd1);

assign j_mid212_op_fu_486_p3 = ((exitcond_flatten_fu_410_p2[0:0] === 1'b1) ? 32'd1 : j_op_fu_480_p2);

assign j_op_fu_480_p2 = (ap_phi_mux_j_phi_fu_252_p4 + 32'd1);

assign out_V_V_din = ((sel_tmp6_fu_353_p2[0:0] === 1'b1) ? p_Result_4_7_fu_1799_p5 : sel_tmp27_fu_1926_p3);

assign p_0219_4_1_fu_1020_p3 = ((sel_tmp6_fu_353_p2[0:0] === 1'b1) ? p_Result_4_1_fu_877_p5 : sel_tmp8_fu_1013_p3);

assign p_0219_4_2_fu_1179_p3 = ((sel_tmp6_fu_353_p2[0:0] === 1'b1) ? p_Result_4_2_fu_1036_p5 : sel_tmp12_fu_1172_p3);

assign p_0219_4_3_fu_1338_p3 = ((sel_tmp6_fu_353_p2[0:0] === 1'b1) ? p_Result_4_3_fu_1195_p5 : sel_tmp15_fu_1331_p3);

assign p_0219_4_4_fu_1510_p3 = ((sel_tmp6_fu_353_p2[0:0] === 1'b1) ? p_Result_4_4_fu_1381_p5 : sel_tmp18_fu_1503_p3);

assign p_0219_4_5_fu_1651_p3 = ((sel_tmp6_fu_353_p2[0:0] === 1'b1) ? p_Result_4_5_fu_1517_p5 : sel_tmp21_fu_1644_p3);

assign p_0219_4_6_fu_1792_p3 = ((sel_tmp6_fu_353_p2[0:0] === 1'b1) ? p_Result_4_6_fu_1658_p5 : sel_tmp24_fu_1785_p3);

assign p_0219_4_fu_861_p3 = ((sel_tmp6_fu_353_p2[0:0] === 1'b1) ? p_Result_4_fu_718_p5 : sel_tmp5_fu_854_p3);

assign p_Result_4_1_fu_877_p5 = {{p_0219_4_fu_861_p3[127:32]}, {p_Result_s_fu_868_p4}, {p_0219_4_fu_861_p3[15:0]}};

assign p_Result_4_2_fu_1036_p5 = {{p_0219_4_1_fu_1020_p3[127:48]}, {p_Result_8_fu_1027_p4}, {p_0219_4_1_fu_1020_p3[31:0]}};

assign p_Result_4_3_fu_1195_p5 = {{p_0219_4_2_fu_1179_p3[127:64]}, {p_Result_9_fu_1186_p4}, {p_0219_4_2_fu_1179_p3[47:0]}};

assign p_Result_4_4_fu_1381_p5 = {{p_0219_4_3_reg_2252[127:80]}, {p_Result_1_reg_2261}, {p_0219_4_3_reg_2252[63:0]}};

assign p_Result_4_5_fu_1517_p5 = {{p_0219_4_4_fu_1510_p3[127:96]}, {p_Result_2_reg_2278}, {p_0219_4_4_fu_1510_p3[79:0]}};

assign p_Result_4_6_fu_1658_p5 = {{p_0219_4_5_fu_1651_p3[127:112]}, {p_Result_3_reg_2295}, {p_0219_4_5_fu_1651_p3[95:0]}};

assign p_Result_4_7_fu_1799_p5 = {{p_Result_10_reg_2312}, {p_0219_4_6_fu_1792_p3[111:0]}};

assign p_Result_4_fu_718_p5 = {{tmp_V_fu_122[127:16]}, {tmp_21_fu_711_p1}};

assign p_Result_5_1_fu_901_p5 = {{p_0219_4_fu_861_p3[127:32]}, {tmp_14_1_fu_894_p3}, {p_0219_4_fu_861_p3[15:0]}};

assign p_Result_5_2_fu_1060_p5 = {{p_0219_4_1_fu_1020_p3[127:48]}, {tmp_14_2_fu_1053_p3}, {p_0219_4_1_fu_1020_p3[31:0]}};

assign p_Result_5_3_fu_1219_p5 = {{p_0219_4_2_fu_1179_p3[127:64]}, {tmp_14_3_fu_1212_p3}, {p_0219_4_2_fu_1179_p3[47:0]}};

assign p_Result_5_4_fu_1401_p5 = {{p_0219_4_3_reg_2252[127:80]}, {tmp_14_4_fu_1395_p3}, {p_0219_4_3_reg_2252[63:0]}};

assign p_Result_5_5_fu_1538_p5 = {{p_0219_4_4_fu_1510_p3[127:96]}, {tmp_14_5_fu_1532_p3}, {p_0219_4_4_fu_1510_p3[79:0]}};

assign p_Result_5_6_fu_1679_p5 = {{p_0219_4_5_fu_1651_p3[127:112]}, {tmp_14_6_fu_1673_p3}, {p_0219_4_5_fu_1651_p3[95:0]}};

assign p_Result_5_7_fu_1820_p5 = {{tmp_14_7_fu_1814_p3}, {p_0219_4_6_fu_1792_p3[111:0]}};

assign p_Result_5_fu_742_p5 = {{tmp_V_fu_122[127:16]}, {tmp_13_fu_735_p3}};

assign p_Result_6_1_fu_937_p5 = {{p_0219_4_fu_861_p3[127:32]}, {tp_d0_V_1_1_fu_929_p3}, {p_0219_4_fu_861_p3[15:0]}};

assign p_Result_6_2_fu_1096_p5 = {{p_0219_4_1_fu_1020_p3[127:48]}, {tp_d0_V_1_2_fu_1088_p3}, {p_0219_4_1_fu_1020_p3[31:0]}};

assign p_Result_6_3_fu_1255_p5 = {{p_0219_4_2_fu_1179_p3[127:64]}, {tp_d0_V_1_3_fu_1247_p3}, {p_0219_4_2_fu_1179_p3[47:0]}};

assign p_Result_6_4_fu_1434_p5 = {{p_0219_4_3_reg_2252[127:80]}, {tp_d0_V_1_4_fu_1427_p3}, {p_0219_4_3_reg_2252[63:0]}};

assign p_Result_6_5_fu_1572_p5 = {{p_0219_4_4_fu_1510_p3[127:96]}, {tp_d0_V_1_5_fu_1565_p3}, {p_0219_4_4_fu_1510_p3[79:0]}};

assign p_Result_6_6_fu_1713_p5 = {{p_0219_4_5_fu_1651_p3[127:112]}, {tp_d0_V_1_6_fu_1706_p3}, {p_0219_4_5_fu_1651_p3[95:0]}};

assign p_Result_6_7_fu_1854_p5 = {{tp_d0_V_1_7_fu_1847_p3}, {p_0219_4_6_fu_1792_p3[111:0]}};

assign p_Result_6_fu_778_p5 = {{tmp_V_fu_122[127:16]}, {tp_d0_V_1_fu_770_p3}};

assign p_Result_7_1_fu_987_p5 = {{p_0219_4_fu_861_p3[127:32]}, {p_in347_ld_1_fu_979_p3}, {p_0219_4_fu_861_p3[15:0]}};

assign p_Result_7_2_fu_1146_p5 = {{p_0219_4_1_fu_1020_p3[127:48]}, {p_in347_ld_2_fu_1138_p3}, {p_0219_4_1_fu_1020_p3[31:0]}};

assign p_Result_7_3_fu_1305_p5 = {{p_0219_4_2_fu_1179_p3[127:64]}, {p_in347_ld_3_fu_1297_p3}, {p_0219_4_2_fu_1179_p3[47:0]}};

assign p_Result_7_4_fu_1479_p5 = {{p_0219_4_3_reg_2252[127:80]}, {p_in347_ld_4_fu_1472_p3}, {p_0219_4_3_reg_2252[63:0]}};

assign p_Result_7_5_fu_1618_p5 = {{p_0219_4_4_fu_1510_p3[127:96]}, {p_in347_ld_5_fu_1611_p3}, {p_0219_4_4_fu_1510_p3[79:0]}};

assign p_Result_7_6_fu_1759_p5 = {{p_0219_4_5_fu_1651_p3[127:112]}, {p_in347_ld_6_fu_1752_p3}, {p_0219_4_5_fu_1651_p3[95:0]}};

assign p_Result_7_7_fu_1900_p5 = {{p_in347_ld_7_fu_1893_p3}, {p_0219_4_6_fu_1792_p3[111:0]}};

assign p_Result_7_fu_828_p5 = {{tmp_V_fu_122[127:16]}, {p_in347_ld_fu_820_p3}};

assign p_Result_8_fu_1027_p4 = {{in_d0_V_reg_2067[47:32]}};

assign p_Result_9_fu_1186_p4 = {{in_d0_V_reg_2067[63:48]}};

assign p_Result_s_fu_868_p4 = {{in_d0_V_reg_2067[31:16]}};

assign p_in347_ld_1_fu_979_p3 = ((tmp_21_1_fu_973_p2[0:0] === 1'b1) ? p_Result_s_fu_868_p4 : tp_d1_V_1_1_fu_966_p3);

assign p_in347_ld_2_fu_1138_p3 = ((tmp_21_2_fu_1132_p2[0:0] === 1'b1) ? p_Result_8_fu_1027_p4 : tp_d1_V_1_2_fu_1125_p3);

assign p_in347_ld_3_fu_1297_p3 = ((tmp_21_3_fu_1291_p2[0:0] === 1'b1) ? p_Result_9_fu_1186_p4 : tp_d1_V_1_3_fu_1284_p3);

assign p_in347_ld_4_fu_1472_p3 = ((tmp_21_4_fu_1467_p2[0:0] === 1'b1) ? p_Result_1_reg_2261 : tp_d1_V_1_4_fu_1460_p3);

assign p_in347_ld_5_fu_1611_p3 = ((tmp_21_5_fu_1606_p2[0:0] === 1'b1) ? p_Result_2_reg_2278 : tp_d1_V_1_5_fu_1599_p3);

assign p_in347_ld_6_fu_1752_p3 = ((tmp_21_6_fu_1747_p2[0:0] === 1'b1) ? p_Result_3_reg_2295 : tp_d1_V_1_6_fu_1740_p3);

assign p_in347_ld_7_fu_1893_p3 = ((tmp_21_7_fu_1888_p2[0:0] === 1'b1) ? p_Result_10_reg_2312 : tp_d1_V_1_7_fu_1881_p3);

assign p_in347_ld_fu_820_p3 = ((tmp_20_fu_814_p2[0:0] === 1'b1) ? tmp_21_fu_711_p1 : tp_d1_V_1_fu_807_p3);

assign ptr_1_fu_618_p3 = ((tmp_12_fu_606_p2[0:0] === 1'b1) ? 32'd0 : ptr_fu_612_p2);

assign ptr_fu_612_p2 = ($signed(ptr_tp_reg_236) + $signed(32'd1));

assign ptr_tp_1_fu_570_p3 = ((tmp_4_fu_555_p2[0:0] === 1'b1) ? ptr_tp_6_fu_560_p2 : ptr_tp_7_fu_565_p2);

assign ptr_tp_2_fu_598_p3 = ((tmp_2_fu_583_p2[0:0] === 1'b1) ? ptr_tp_8_fu_588_p2 : ptr_tp_9_fu_593_p2);

assign ptr_tp_3_fu_532_p2 = ($signed(tmp_fu_329_p2) + $signed(ptr_tp_reg_236));

assign ptr_tp_4_fu_537_p2 = ($signed(ptr_tp_reg_236) - $signed(width_out));

assign ptr_tp_5_fu_542_p3 = ((tmp_s_fu_527_p2[0:0] === 1'b1) ? ptr_tp_3_fu_532_p2 : ptr_tp_4_fu_537_p2);

assign ptr_tp_6_fu_560_p2 = ($signed(tmp_fu_329_p2) + $signed(ptr_tp_5_fu_542_p3));

assign ptr_tp_7_fu_565_p2 = ($signed(ptr_tp_5_fu_542_p3) - $signed(width_out));

assign ptr_tp_8_fu_588_p2 = ($signed(tmp_fu_329_p2) + $signed(ptr_tp_1_fu_570_p3));

assign ptr_tp_9_fu_593_p2 = ($signed(ptr_tp_1_fu_570_p3) - $signed(width_out));

assign sel_tmp10_fu_1158_p3 = ((sel_tmp_fu_335_p2[0:0] === 1'b1) ? p_Result_7_2_fu_1146_p5 : p_0219_4_1_fu_1020_p3);

assign sel_tmp11_fu_1165_p3 = ((sel_tmp2_fu_341_p2[0:0] === 1'b1) ? p_Result_6_2_fu_1096_p5 : sel_tmp10_fu_1158_p3);

assign sel_tmp12_fu_1172_p3 = ((sel_tmp4_fu_347_p2[0:0] === 1'b1) ? p_Result_5_2_fu_1060_p5 : sel_tmp11_fu_1165_p3);

assign sel_tmp13_fu_1317_p3 = ((sel_tmp_fu_335_p2[0:0] === 1'b1) ? p_Result_7_3_fu_1305_p5 : p_0219_4_2_fu_1179_p3);

assign sel_tmp14_fu_1324_p3 = ((sel_tmp2_fu_341_p2[0:0] === 1'b1) ? p_Result_6_3_fu_1255_p5 : sel_tmp13_fu_1317_p3);

assign sel_tmp15_fu_1331_p3 = ((sel_tmp4_fu_347_p2[0:0] === 1'b1) ? p_Result_5_3_fu_1219_p5 : sel_tmp14_fu_1324_p3);

assign sel_tmp16_fu_1490_p3 = ((sel_tmp_fu_335_p2[0:0] === 1'b1) ? p_Result_7_4_fu_1479_p5 : p_0219_4_3_reg_2252);

assign sel_tmp17_fu_1496_p3 = ((sel_tmp2_fu_341_p2[0:0] === 1'b1) ? p_Result_6_4_fu_1434_p5 : sel_tmp16_fu_1490_p3);

assign sel_tmp18_fu_1503_p3 = ((sel_tmp4_fu_347_p2[0:0] === 1'b1) ? p_Result_5_4_fu_1401_p5 : sel_tmp17_fu_1496_p3);

assign sel_tmp19_fu_1630_p3 = ((sel_tmp_fu_335_p2[0:0] === 1'b1) ? p_Result_7_5_fu_1618_p5 : p_0219_4_4_fu_1510_p3);

assign sel_tmp1_fu_840_p3 = ((sel_tmp_fu_335_p2[0:0] === 1'b1) ? p_Result_7_fu_828_p5 : tmp_V_fu_122);

assign sel_tmp20_fu_1637_p3 = ((sel_tmp2_fu_341_p2[0:0] === 1'b1) ? p_Result_6_5_fu_1572_p5 : sel_tmp19_fu_1630_p3);

assign sel_tmp21_fu_1644_p3 = ((sel_tmp4_fu_347_p2[0:0] === 1'b1) ? p_Result_5_5_fu_1538_p5 : sel_tmp20_fu_1637_p3);

assign sel_tmp22_fu_1771_p3 = ((sel_tmp_fu_335_p2[0:0] === 1'b1) ? p_Result_7_6_fu_1759_p5 : p_0219_4_5_fu_1651_p3);

assign sel_tmp23_fu_1778_p3 = ((sel_tmp2_fu_341_p2[0:0] === 1'b1) ? p_Result_6_6_fu_1713_p5 : sel_tmp22_fu_1771_p3);

assign sel_tmp24_fu_1785_p3 = ((sel_tmp4_fu_347_p2[0:0] === 1'b1) ? p_Result_5_6_fu_1679_p5 : sel_tmp23_fu_1778_p3);

assign sel_tmp25_fu_1912_p3 = ((sel_tmp_fu_335_p2[0:0] === 1'b1) ? p_Result_7_7_fu_1900_p5 : p_0219_4_6_fu_1792_p3);

assign sel_tmp26_fu_1919_p3 = ((sel_tmp2_fu_341_p2[0:0] === 1'b1) ? p_Result_6_7_fu_1854_p5 : sel_tmp25_fu_1912_p3);

assign sel_tmp27_fu_1926_p3 = ((sel_tmp4_fu_347_p2[0:0] === 1'b1) ? p_Result_5_7_fu_1820_p5 : sel_tmp26_fu_1919_p3);

assign sel_tmp2_fu_341_p2 = ((Ky == 32'd3) ? 1'b1 : 1'b0);

assign sel_tmp3_fu_847_p3 = ((sel_tmp2_fu_341_p2[0:0] === 1'b1) ? p_Result_6_fu_778_p5 : sel_tmp1_fu_840_p3);

assign sel_tmp4_fu_347_p2 = ((Ky == 32'd2) ? 1'b1 : 1'b0);

assign sel_tmp5_fu_854_p3 = ((sel_tmp4_fu_347_p2[0:0] === 1'b1) ? p_Result_5_fu_742_p5 : sel_tmp3_fu_847_p3);

assign sel_tmp6_fu_353_p2 = ((Ky == 32'd1) ? 1'b1 : 1'b0);

assign sel_tmp7_fu_1006_p3 = ((sel_tmp2_fu_341_p2[0:0] === 1'b1) ? p_Result_6_1_fu_937_p5 : sel_tmp9_fu_999_p3);

assign sel_tmp8_fu_1013_p3 = ((sel_tmp4_fu_347_p2[0:0] === 1'b1) ? p_Result_5_1_fu_901_p5 : sel_tmp7_fu_1006_p3);

assign sel_tmp9_fu_999_p3 = ((sel_tmp_fu_335_p2[0:0] === 1'b1) ? p_Result_7_1_fu_987_p5 : p_0219_4_fu_861_p3);

assign sel_tmp_fu_335_p2 = ((Ky == 32'd4) ? 1'b1 : 1'b0);

assign tmp_10_fu_626_p1 = $signed(ptr_tp_2_reg_2093);

assign tmp_11_fu_730_p2 = (($signed(tmp_21_fu_711_p1) > $signed(tmp_22_reg_2108)) ? 1'b1 : 1'b0);

assign tmp_12_fu_606_p2 = ((ptr_tp_reg_236 == 32'd127) ? 1'b1 : 1'b0);

assign tmp_13_1_fu_889_p2 = (($signed(p_Result_s_fu_868_p4) > $signed(p_Result_1_1_reg_2126)) ? 1'b1 : 1'b0);

assign tmp_13_2_fu_1048_p2 = (($signed(p_Result_8_fu_1027_p4) > $signed(p_Result_1_2_reg_2144)) ? 1'b1 : 1'b0);

assign tmp_13_3_fu_1207_p2 = (($signed(p_Result_9_fu_1186_p4) > $signed(p_Result_1_3_reg_2162)) ? 1'b1 : 1'b0);

assign tmp_13_4_fu_1391_p2 = (($signed(p_Result_1_reg_2261) > $signed(p_Result_1_4_reg_2180)) ? 1'b1 : 1'b0);

assign tmp_13_5_fu_1528_p2 = (($signed(p_Result_2_reg_2278) > $signed(p_Result_1_5_reg_2198)) ? 1'b1 : 1'b0);

assign tmp_13_6_fu_1669_p2 = (($signed(p_Result_3_reg_2295) > $signed(p_Result_1_6_reg_2216)) ? 1'b1 : 1'b0);

assign tmp_13_7_fu_1810_p2 = (($signed(p_Result_10_reg_2312) > $signed(p_Result_1_7_reg_2234)) ? 1'b1 : 1'b0);

assign tmp_13_fu_735_p3 = ((tmp_11_fu_730_p2[0:0] === 1'b1) ? tmp_21_fu_711_p1 : tmp_22_reg_2108);

assign tmp_14_1_fu_894_p3 = ((tmp_13_1_fu_889_p2[0:0] === 1'b1) ? p_Result_s_fu_868_p4 : p_Result_1_1_reg_2126);

assign tmp_14_2_fu_1053_p3 = ((tmp_13_2_fu_1048_p2[0:0] === 1'b1) ? p_Result_8_fu_1027_p4 : p_Result_1_2_reg_2144);

assign tmp_14_3_fu_1212_p3 = ((tmp_13_3_fu_1207_p2[0:0] === 1'b1) ? p_Result_9_fu_1186_p4 : p_Result_1_3_reg_2162);

assign tmp_14_4_fu_1395_p3 = ((tmp_13_4_fu_1391_p2[0:0] === 1'b1) ? p_Result_1_reg_2261 : p_Result_1_4_reg_2180);

assign tmp_14_5_fu_1532_p3 = ((tmp_13_5_fu_1528_p2[0:0] === 1'b1) ? p_Result_2_reg_2278 : p_Result_1_5_reg_2198);

assign tmp_14_6_fu_1673_p3 = ((tmp_13_6_fu_1669_p2[0:0] === 1'b1) ? p_Result_3_reg_2295 : p_Result_1_6_reg_2216);

assign tmp_14_7_fu_1814_p3 = ((tmp_13_7_fu_1810_p2[0:0] === 1'b1) ? p_Result_10_reg_2312 : p_Result_1_7_reg_2234);

assign tmp_14_fu_754_p2 = (($signed(tmp_22_reg_2108) > $signed(tmp_23_reg_2118)) ? 1'b1 : 1'b0);

assign tmp_15_1_fu_913_p2 = (($signed(p_Result_1_1_reg_2126) > $signed(p_Result_2_1_reg_2136)) ? 1'b1 : 1'b0);

assign tmp_15_2_fu_1072_p2 = (($signed(p_Result_1_2_reg_2144) > $signed(p_Result_2_2_reg_2154)) ? 1'b1 : 1'b0);

assign tmp_15_3_fu_1231_p2 = (($signed(p_Result_1_3_reg_2162) > $signed(p_Result_2_3_reg_2172)) ? 1'b1 : 1'b0);

assign tmp_15_4_fu_1412_p2 = (($signed(p_Result_1_4_reg_2180) > $signed(p_Result_2_4_reg_2190)) ? 1'b1 : 1'b0);

assign tmp_15_5_fu_1550_p2 = (($signed(p_Result_1_5_reg_2198) > $signed(p_Result_2_5_reg_2208)) ? 1'b1 : 1'b0);

assign tmp_15_6_fu_1691_p2 = (($signed(p_Result_1_6_reg_2216) > $signed(p_Result_2_6_reg_2226)) ? 1'b1 : 1'b0);

assign tmp_15_7_fu_1832_p2 = (($signed(p_Result_1_7_reg_2234) > $signed(p_Result_2_7_reg_2244)) ? 1'b1 : 1'b0);

assign tmp_15_fu_758_p3 = ((tmp_14_fu_754_p2[0:0] === 1'b1) ? tmp_22_reg_2108 : tmp_23_reg_2118);

assign tmp_16_1_fu_917_p3 = ((tmp_15_1_fu_913_p2[0:0] === 1'b1) ? p_Result_1_1_reg_2126 : p_Result_2_1_reg_2136);

assign tmp_16_2_fu_1076_p3 = ((tmp_15_2_fu_1072_p2[0:0] === 1'b1) ? p_Result_1_2_reg_2144 : p_Result_2_2_reg_2154);

assign tmp_16_3_fu_1235_p3 = ((tmp_15_3_fu_1231_p2[0:0] === 1'b1) ? p_Result_1_3_reg_2162 : p_Result_2_3_reg_2172);

assign tmp_16_4_fu_1416_p3 = ((tmp_15_4_fu_1412_p2[0:0] === 1'b1) ? p_Result_1_4_reg_2180 : p_Result_2_4_reg_2190);

assign tmp_16_5_fu_1554_p3 = ((tmp_15_5_fu_1550_p2[0:0] === 1'b1) ? p_Result_1_5_reg_2198 : p_Result_2_5_reg_2208);

assign tmp_16_6_fu_1695_p3 = ((tmp_15_6_fu_1691_p2[0:0] === 1'b1) ? p_Result_1_6_reg_2216 : p_Result_2_6_reg_2226);

assign tmp_16_7_fu_1836_p3 = ((tmp_15_7_fu_1832_p2[0:0] === 1'b1) ? p_Result_1_7_reg_2234 : p_Result_2_7_reg_2244);

assign tmp_16_fu_764_p2 = (($signed(tmp_21_fu_711_p1) > $signed(tmp_15_fu_758_p3)) ? 1'b1 : 1'b0);

assign tmp_17_1_fu_923_p2 = (($signed(p_Result_s_fu_868_p4) > $signed(tmp_16_1_fu_917_p3)) ? 1'b1 : 1'b0);

assign tmp_17_2_fu_1082_p2 = (($signed(p_Result_8_fu_1027_p4) > $signed(tmp_16_2_fu_1076_p3)) ? 1'b1 : 1'b0);

assign tmp_17_3_fu_1241_p2 = (($signed(p_Result_9_fu_1186_p4) > $signed(tmp_16_3_fu_1235_p3)) ? 1'b1 : 1'b0);

assign tmp_17_4_fu_1422_p2 = (($signed(p_Result_1_reg_2261) > $signed(tmp_16_4_fu_1416_p3)) ? 1'b1 : 1'b0);

assign tmp_17_5_fu_1560_p2 = (($signed(p_Result_2_reg_2278) > $signed(tmp_16_5_fu_1554_p3)) ? 1'b1 : 1'b0);

assign tmp_17_6_fu_1701_p2 = (($signed(p_Result_3_reg_2295) > $signed(tmp_16_6_fu_1695_p3)) ? 1'b1 : 1'b0);

assign tmp_17_7_fu_1842_p2 = (($signed(p_Result_10_reg_2312) > $signed(tmp_16_7_fu_1836_p3)) ? 1'b1 : 1'b0);

assign tmp_17_fu_790_p2 = (($signed(tmp_23_reg_2118) > $signed(tmp_24_fu_714_p1)) ? 1'b1 : 1'b0);

assign tmp_18_1_fu_949_p2 = (($signed(p_Result_2_1_reg_2136) > $signed(grp_fu_259_p4)) ? 1'b1 : 1'b0);

assign tmp_18_2_fu_1108_p2 = (($signed(p_Result_2_2_reg_2154) > $signed(grp_fu_269_p4)) ? 1'b1 : 1'b0);

assign tmp_18_3_fu_1267_p2 = (($signed(p_Result_2_3_reg_2172) > $signed(grp_fu_279_p4)) ? 1'b1 : 1'b0);

assign tmp_18_4_fu_1445_p2 = (($signed(p_Result_2_4_reg_2190) > $signed(p_Result_3_4_reg_2272)) ? 1'b1 : 1'b0);

assign tmp_18_5_fu_1584_p2 = (($signed(p_Result_2_5_reg_2208) > $signed(p_Result_3_5_reg_2289)) ? 1'b1 : 1'b0);

assign tmp_18_6_fu_1725_p2 = (($signed(p_Result_2_6_reg_2226) > $signed(p_Result_3_6_reg_2306)) ? 1'b1 : 1'b0);

assign tmp_18_7_fu_1866_p2 = (($signed(p_Result_2_7_reg_2244) > $signed(p_Result_3_7_reg_2323)) ? 1'b1 : 1'b0);

assign tmp_18_fu_795_p3 = ((tmp_17_fu_790_p2[0:0] === 1'b1) ? tmp_23_reg_2118 : tmp_24_fu_714_p1);

assign tmp_19_1_fu_954_p3 = ((tmp_18_1_fu_949_p2[0:0] === 1'b1) ? p_Result_2_1_reg_2136 : grp_fu_259_p4);

assign tmp_19_2_fu_1113_p3 = ((tmp_18_2_fu_1108_p2[0:0] === 1'b1) ? p_Result_2_2_reg_2154 : grp_fu_269_p4);

assign tmp_19_3_fu_1272_p3 = ((tmp_18_3_fu_1267_p2[0:0] === 1'b1) ? p_Result_2_3_reg_2172 : grp_fu_279_p4);

assign tmp_19_4_fu_1449_p3 = ((tmp_18_4_fu_1445_p2[0:0] === 1'b1) ? p_Result_2_4_reg_2190 : p_Result_3_4_reg_2272);

assign tmp_19_5_fu_1588_p3 = ((tmp_18_5_fu_1584_p2[0:0] === 1'b1) ? p_Result_2_5_reg_2208 : p_Result_3_5_reg_2289);

assign tmp_19_6_fu_1729_p3 = ((tmp_18_6_fu_1725_p2[0:0] === 1'b1) ? p_Result_2_6_reg_2226 : p_Result_3_6_reg_2306);

assign tmp_19_7_fu_1870_p3 = ((tmp_18_7_fu_1866_p2[0:0] === 1'b1) ? p_Result_2_7_reg_2244 : p_Result_3_7_reg_2323);

assign tmp_19_fu_802_p2 = (($signed(tmp_22_reg_2108) > $signed(tmp_18_fu_795_p3)) ? 1'b1 : 1'b0);

assign tmp_20_1_fu_961_p2 = (($signed(p_Result_1_1_reg_2126) > $signed(tmp_19_1_fu_954_p3)) ? 1'b1 : 1'b0);

assign tmp_20_2_fu_1120_p2 = (($signed(p_Result_1_2_reg_2144) > $signed(tmp_19_2_fu_1113_p3)) ? 1'b1 : 1'b0);

assign tmp_20_3_fu_1279_p2 = (($signed(p_Result_1_3_reg_2162) > $signed(tmp_19_3_fu_1272_p3)) ? 1'b1 : 1'b0);

assign tmp_20_4_fu_1455_p2 = (($signed(p_Result_1_4_reg_2180) > $signed(tmp_19_4_fu_1449_p3)) ? 1'b1 : 1'b0);

assign tmp_20_5_fu_1594_p2 = (($signed(p_Result_1_5_reg_2198) > $signed(tmp_19_5_fu_1588_p3)) ? 1'b1 : 1'b0);

assign tmp_20_6_fu_1735_p2 = (($signed(p_Result_1_6_reg_2216) > $signed(tmp_19_6_fu_1729_p3)) ? 1'b1 : 1'b0);

assign tmp_20_7_fu_1876_p2 = (($signed(p_Result_1_7_reg_2234) > $signed(tmp_19_7_fu_1870_p3)) ? 1'b1 : 1'b0);

assign tmp_20_fu_814_p2 = (($signed(tmp_21_fu_711_p1) > $signed(tp_d1_V_1_fu_807_p3)) ? 1'b1 : 1'b0);

assign tmp_21_1_fu_973_p2 = (($signed(p_Result_s_fu_868_p4) > $signed(tp_d1_V_1_1_fu_966_p3)) ? 1'b1 : 1'b0);

assign tmp_21_2_fu_1132_p2 = (($signed(p_Result_8_fu_1027_p4) > $signed(tp_d1_V_1_2_fu_1125_p3)) ? 1'b1 : 1'b0);

assign tmp_21_3_fu_1291_p2 = (($signed(p_Result_9_fu_1186_p4) > $signed(tp_d1_V_1_3_fu_1284_p3)) ? 1'b1 : 1'b0);

assign tmp_21_4_fu_1467_p2 = (($signed(p_Result_1_reg_2261) > $signed(tp_d1_V_1_4_fu_1460_p3)) ? 1'b1 : 1'b0);

assign tmp_21_5_fu_1606_p2 = (($signed(p_Result_2_reg_2278) > $signed(tp_d1_V_1_5_fu_1599_p3)) ? 1'b1 : 1'b0);

assign tmp_21_6_fu_1747_p2 = (($signed(p_Result_3_reg_2295) > $signed(tp_d1_V_1_6_fu_1740_p3)) ? 1'b1 : 1'b0);

assign tmp_21_7_fu_1888_p2 = (($signed(p_Result_10_reg_2312) > $signed(tp_d1_V_1_7_fu_1881_p3)) ? 1'b1 : 1'b0);

assign tmp_21_fu_711_p1 = in_d0_V_reg_2067[15:0];

assign tmp_22_fu_630_p1 = buf_V_q0[15:0];

assign tmp_23_fu_634_p1 = buf_V_q1[15:0];

assign tmp_24_fu_714_p1 = buf_V_q0[15:0];

assign tmp_2_fu_583_p2 = (($signed(ptr_tp_1_fu_570_p3) < $signed(width_out)) ? 1'b1 : 1'b0);

assign tmp_3_fu_550_p1 = ptr_tp_5_fu_542_p3;

assign tmp_4_fu_555_p2 = (($signed(ptr_tp_5_fu_542_p3) < $signed(width_out)) ? 1'b1 : 1'b0);

assign tmp_5_fu_431_p2 = (($signed(ap_phi_mux_j_phi_fu_252_p4) < $signed(width_out)) ? 1'b1 : 1'b0);

assign tmp_5_mid1_fu_436_p3 = ((exitcond_flatten_fu_410_p2[0:0] === 1'b1) ? tmp_5_mid_fu_387_p2 : tmp_5_fu_431_p2);

assign tmp_5_mid_fu_387_p2 = (($signed(width_out) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign tmp_6_fu_516_p1 = ap_phi_mux_ptr_tp_phi_fu_240_p4;

assign tmp_7_fu_578_p1 = ptr_tp_1_fu_570_p3;

assign tmp_9_fu_521_p2 = ((grp_fu_475_p2 == 32'd0) ? 1'b1 : 1'b0);

assign tmp_V_2_fu_1933_p3 = ((sel_tmp6_fu_353_p2[0:0] === 1'b1) ? p_Result_4_7_fu_1799_p5 : sel_tmp27_fu_1926_p3);

assign tmp_fu_329_p2 = (32'd128 - width_out);

assign tmp_s_fu_527_p2 = (($signed(ptr_tp_reg_236) < $signed(width_out)) ? 1'b1 : 1'b0);

assign tp_d0_V_1_1_fu_929_p3 = ((tmp_17_1_fu_923_p2[0:0] === 1'b1) ? p_Result_s_fu_868_p4 : tmp_16_1_fu_917_p3);

assign tp_d0_V_1_2_fu_1088_p3 = ((tmp_17_2_fu_1082_p2[0:0] === 1'b1) ? p_Result_8_fu_1027_p4 : tmp_16_2_fu_1076_p3);

assign tp_d0_V_1_3_fu_1247_p3 = ((tmp_17_3_fu_1241_p2[0:0] === 1'b1) ? p_Result_9_fu_1186_p4 : tmp_16_3_fu_1235_p3);

assign tp_d0_V_1_4_fu_1427_p3 = ((tmp_17_4_fu_1422_p2[0:0] === 1'b1) ? p_Result_1_reg_2261 : tmp_16_4_fu_1416_p3);

assign tp_d0_V_1_5_fu_1565_p3 = ((tmp_17_5_fu_1560_p2[0:0] === 1'b1) ? p_Result_2_reg_2278 : tmp_16_5_fu_1554_p3);

assign tp_d0_V_1_6_fu_1706_p3 = ((tmp_17_6_fu_1701_p2[0:0] === 1'b1) ? p_Result_3_reg_2295 : tmp_16_6_fu_1695_p3);

assign tp_d0_V_1_7_fu_1847_p3 = ((tmp_17_7_fu_1842_p2[0:0] === 1'b1) ? p_Result_10_reg_2312 : tmp_16_7_fu_1836_p3);

assign tp_d0_V_1_fu_770_p3 = ((tmp_16_fu_764_p2[0:0] === 1'b1) ? tmp_21_fu_711_p1 : tmp_15_fu_758_p3);

assign tp_d1_V_1_1_fu_966_p3 = ((tmp_20_1_fu_961_p2[0:0] === 1'b1) ? p_Result_1_1_reg_2126 : tmp_19_1_fu_954_p3);

assign tp_d1_V_1_2_fu_1125_p3 = ((tmp_20_2_fu_1120_p2[0:0] === 1'b1) ? p_Result_1_2_reg_2144 : tmp_19_2_fu_1113_p3);

assign tp_d1_V_1_3_fu_1284_p3 = ((tmp_20_3_fu_1279_p2[0:0] === 1'b1) ? p_Result_1_3_reg_2162 : tmp_19_3_fu_1272_p3);

assign tp_d1_V_1_4_fu_1460_p3 = ((tmp_20_4_fu_1455_p2[0:0] === 1'b1) ? p_Result_1_4_reg_2180 : tmp_19_4_fu_1449_p3);

assign tp_d1_V_1_5_fu_1599_p3 = ((tmp_20_5_fu_1594_p2[0:0] === 1'b1) ? p_Result_1_5_reg_2198 : tmp_19_5_fu_1588_p3);

assign tp_d1_V_1_6_fu_1740_p3 = ((tmp_20_6_fu_1735_p2[0:0] === 1'b1) ? p_Result_1_6_reg_2216 : tmp_19_6_fu_1729_p3);

assign tp_d1_V_1_7_fu_1881_p3 = ((tmp_20_7_fu_1876_p2[0:0] === 1'b1) ? p_Result_1_7_reg_2234 : tmp_19_7_fu_1870_p3);

assign tp_d1_V_1_fu_807_p3 = ((tmp_19_fu_802_p2[0:0] === 1'b1) ? tmp_22_reg_2108 : tmp_18_fu_795_p3);

endmodule //pool_2D
