// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// ==============================================================

#define AP_INT_MAX_W 32678

#include <systemc>
#include <iostream>
#include <cstdlib>
#include <cstddef>
#include <stdint.h>
#include "SysCFileHandler.h"
#include "ap_int.h"
#include "ap_fixed.h"
#include <complex>
#include <stdbool.h>
#include "autopilot_cbe.h"
#include "ap_stream.h"
#include "hls_stream.h"
#include "hls_half.h"
#include "hls_signal_handler.h"

using namespace std;
using namespace sc_core;
using namespace sc_dt;


// [dump_struct_tree [build_nameSpaceTree] dumpedStructList] ---------->
    typedef struct  {
        ap_int<128> data;
        bool last;
       } dtype_stream;



// [dump_enumeration [get_enumeration_list]] ---------->


// wrapc file define: "in_V_V"
#define AUTOTB_TVIN_in_V_V  "../tv/cdatafile/c.pool.autotvin_in_V_V.dat"
#define WRAPC_STREAM_SIZE_IN_in_V_V  "../tv/stream_size/stream_size_in_in_V_V.dat"
#define WRAPC_STREAM_INGRESS_STATUS_in_V_V  "../tv/stream_size/stream_ingress_status_in_V_V.dat"
// wrapc file define: "out_V_data_V"
#define AUTOTB_TVOUT_out_V_data_V  "../tv/cdatafile/c.pool.autotvout_out_V_data_V.dat"
#define AUTOTB_TVIN_out_V_data_V  "../tv/cdatafile/c.pool.autotvin_out_V_data_V.dat"
#define WRAPC_STREAM_SIZE_OUT_out_V_data_V  "../tv/stream_size/stream_size_out_out_V_data_V.dat"
#define WRAPC_STREAM_EGRESS_STATUS_out_V_data_V  "../tv/stream_size/stream_egress_status_out_V_data_V.dat"
// wrapc file define: "out_V_last"
#define AUTOTB_TVOUT_out_V_last  "../tv/cdatafile/c.pool.autotvout_out_V_last.dat"
#define AUTOTB_TVIN_out_V_last  "../tv/cdatafile/c.pool.autotvin_out_V_last.dat"
#define WRAPC_STREAM_SIZE_OUT_out_V_last  "../tv/stream_size/stream_size_out_out_V_last.dat"
#define WRAPC_STREAM_EGRESS_STATUS_out_V_last  "../tv/stream_size/stream_egress_status_out_V_last.dat"
// wrapc file define: "ch_div_K"
#define AUTOTB_TVIN_ch_div_K  "../tv/cdatafile/c.pool.autotvin_ch_div_K.dat"
// wrapc file define: "height_in"
#define AUTOTB_TVIN_height_in  "../tv/cdatafile/c.pool.autotvin_height_in.dat"
// wrapc file define: "width_in"
#define AUTOTB_TVIN_width_in  "../tv/cdatafile/c.pool.autotvin_width_in.dat"
// wrapc file define: "height_out"
#define AUTOTB_TVIN_height_out  "../tv/cdatafile/c.pool.autotvin_height_out.dat"
// wrapc file define: "width_out"
#define AUTOTB_TVIN_width_out  "../tv/cdatafile/c.pool.autotvin_width_out.dat"
// wrapc file define: "Kx"
#define AUTOTB_TVIN_Kx  "../tv/cdatafile/c.pool.autotvin_Kx.dat"
// wrapc file define: "Ky"
#define AUTOTB_TVIN_Ky  "../tv/cdatafile/c.pool.autotvin_Ky.dat"

#define INTER_TCL  "../tv/cdatafile/ref.tcl"

// tvout file define: "out_V_data_V"
#define AUTOTB_TVOUT_PC_out_V_data_V  "../tv/rtldatafile/rtl.pool.autotvout_out_V_data_V.dat"
// tvout file define: "out_V_last"
#define AUTOTB_TVOUT_PC_out_V_last  "../tv/rtldatafile/rtl.pool.autotvout_out_V_last.dat"

class INTER_TCL_FILE {
	public:
		INTER_TCL_FILE(const char* name) {
			mName = name;
			in_V_V_depth = 0;
			out_V_data_V_depth = 0;
			out_V_last_depth = 0;
			ch_div_K_depth = 0;
			height_in_depth = 0;
			width_in_depth = 0;
			height_out_depth = 0;
			width_out_depth = 0;
			Kx_depth = 0;
			Ky_depth = 0;
			trans_num =0;
		}

		~INTER_TCL_FILE() {
			mFile.open(mName);
			if (!mFile.good()) {
				cout << "Failed to open file ref.tcl" << endl;
				exit (1);
			}
			string total_list = get_depth_list();
			mFile << "set depth_list {\n";
			mFile << total_list;
			mFile << "}\n";
			mFile << "set trans_num "<<trans_num<<endl;
			mFile.close();
		}

		string get_depth_list () {
			stringstream total_list;
			total_list << "{in_V_V " << in_V_V_depth << "}\n";
			total_list << "{out_V_data_V " << out_V_data_V_depth << "}\n";
			total_list << "{out_V_last " << out_V_last_depth << "}\n";
			total_list << "{ch_div_K " << ch_div_K_depth << "}\n";
			total_list << "{height_in " << height_in_depth << "}\n";
			total_list << "{width_in " << width_in_depth << "}\n";
			total_list << "{height_out " << height_out_depth << "}\n";
			total_list << "{width_out " << width_out_depth << "}\n";
			total_list << "{Kx " << Kx_depth << "}\n";
			total_list << "{Ky " << Ky_depth << "}\n";
			return total_list.str();
		}

		void set_num (int num , int* class_num) {
			(*class_num) = (*class_num) > num ? (*class_num) : num;
		}
	public:
		int in_V_V_depth;
		int out_V_data_V_depth;
		int out_V_last_depth;
		int ch_div_K_depth;
		int height_in_depth;
		int width_in_depth;
		int height_out_depth;
		int width_out_depth;
		int Kx_depth;
		int Ky_depth;
		int trans_num;

	private:
		ofstream mFile;
		const char* mName;
};

extern void pool (
hls::stream<ap_int<128> > (&in),
hls::stream<dtype_stream > (&out),
int ch_div_K,
int height_in,
int width_in,
int height_out,
int width_out,
int Kx,
int Ky);

void AESL_WRAP_pool (
hls::stream<ap_int<128> > (&in),
hls::stream<dtype_stream > (&out),
int ch_div_K,
int height_in,
int width_in,
int height_out,
int width_out,
int Kx,
int Ky)
{
	refine_signal_handler();
	fstream wrapc_switch_file_token;
	wrapc_switch_file_token.open(".hls_cosim_wrapc_switch.log");
	int AESL_i;
	if (wrapc_switch_file_token.good())
	{
		CodeState = ENTER_WRAPC_PC;
		static unsigned AESL_transaction_pc = 0;
		string AESL_token;
		string AESL_num;
		static AESL_FILE_HANDLER aesl_fh;

		// pop stream input: "in"
		aesl_fh.read(WRAPC_STREAM_SIZE_IN_in_V_V, AESL_token); // [[transaction]]
		aesl_fh.read(WRAPC_STREAM_SIZE_IN_in_V_V, AESL_num); // transaction number

		if (atoi(AESL_num.c_str()) == AESL_transaction_pc)
		{
			aesl_fh.read(WRAPC_STREAM_SIZE_IN_in_V_V, AESL_token); // pop_size
			int aesl_tmp_1 = atoi(AESL_token.c_str());
			for (int i = 0; i < aesl_tmp_1; i++)
			{
				in.read();
			}
			aesl_fh.read(WRAPC_STREAM_SIZE_IN_in_V_V, AESL_token); // [[/transaction]]
		}

		// define output stream variables: "out"
		std::vector<dtype_stream > aesl_tmp_3;
		int aesl_tmp_4;
		int aesl_tmp_5 = 0;

		// read output stream size: "out"
		aesl_fh.read(WRAPC_STREAM_SIZE_OUT_out_V_data_V, AESL_token); // [[transaction]]
		aesl_fh.read(WRAPC_STREAM_SIZE_OUT_out_V_data_V, AESL_num); // transaction number

		if (atoi(AESL_num.c_str()) == AESL_transaction_pc)
		{
			aesl_fh.read(WRAPC_STREAM_SIZE_OUT_out_V_data_V, AESL_token); // pop_size
			aesl_tmp_4 = atoi(AESL_token.c_str());
			aesl_fh.read(WRAPC_STREAM_SIZE_OUT_out_V_data_V, AESL_token); // [[/transaction]]
		}

		// output port post check: "out_V_data_V"
		aesl_fh.read(AUTOTB_TVOUT_PC_out_V_data_V, AESL_token); // [[transaction]]
		if (AESL_token != "[[transaction]]")
		{
			exit(1);
		}
		aesl_fh.read(AUTOTB_TVOUT_PC_out_V_data_V, AESL_num); // transaction number

		if (atoi(AESL_num.c_str()) == AESL_transaction_pc)
		{
			aesl_fh.read(AUTOTB_TVOUT_PC_out_V_data_V, AESL_token); // data

			std::vector<sc_bv<128> > out_V_data_V_pc_buffer;
			int i = 0;

			while (AESL_token != "[[/transaction]]")
			{
				bool no_x = false;
				bool err = false;

				// search and replace 'X' with "0" from the 1st char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('X');
					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "WARNING: [SIM 212-201] RTL produces unknown value 'X' on port 'out_V_data_V', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				no_x = false;

				// search and replace 'x' with "0" from the 3rd char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('x', 2);

					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "WARNING: [SIM 212-201] RTL produces unknown value 'X' on port 'out_V_data_V', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				// push token into output port buffer
				if (AESL_token != "")
				{
					out_V_data_V_pc_buffer.push_back(AESL_token.c_str());
					i++;
				}

				aesl_fh.read(AUTOTB_TVOUT_PC_out_V_data_V, AESL_token); // data or [[/transaction]]

				if (AESL_token == "[[[/runtime]]]" || aesl_fh.eof(AUTOTB_TVOUT_PC_out_V_data_V))
				{
					exit(1);
				}
			}

			// correct the buffer size the current transaction
			if (i != aesl_tmp_4)
			{
				aesl_tmp_4 = i;
			}

			if (aesl_tmp_4 > 0 && aesl_tmp_3.size() < aesl_tmp_4)
			{
				int aesl_tmp_3_size = aesl_tmp_3.size();

				for (int tmp_aesl_tmp_3 = 0; tmp_aesl_tmp_3 < aesl_tmp_4 - aesl_tmp_3_size; tmp_aesl_tmp_3++)
				{
					dtype_stream tmp;
					aesl_tmp_3.push_back(tmp);
				}
			}

			// ***********************************
			if (i > 0)
			{
				// RTL Name: out_V_data_V
				{
					// bitslice(127, 0)
					// {
						// celement: out.V.data.V(127, 0)
						// {
							sc_lv<128>* out_V_data_V_lv0_0_0_1_lv1_0_0_1 = new sc_lv<128>[aesl_tmp_4 - aesl_tmp_5];
						// }
					// }

					// bitslice(127, 0)
					{
						int hls_map_index = 0;
						// celement: out.V.data.V(127, 0)
						{
							// carray: (aesl_tmp_5) => (aesl_tmp_4 - 1) @ (1)
							for (int i_0 = aesl_tmp_5; i_0 <= aesl_tmp_4 - 1; i_0 += 1)
							{
								// carray: (0) => (0) @ (1)
								for (int i_1 = 0; i_1 <= 0; i_1 += 1)
								{
									if (&(aesl_tmp_3[0].data) != NULL) // check the null address if the c port is array or others
									{
										out_V_data_V_lv0_0_0_1_lv1_0_0_1[hls_map_index].range(127, 0) = sc_bv<128>(out_V_data_V_pc_buffer[hls_map_index].range(127, 0));
										hls_map_index++;
									}
								}
							}
						}
					}

					// bitslice(127, 0)
					{
						int hls_map_index = 0;
						// celement: out.V.data.V(127, 0)
						{
							// carray: (aesl_tmp_5) => (aesl_tmp_4 - 1) @ (1)
							for (int i_0 = aesl_tmp_5; i_0 <= aesl_tmp_4 - 1; i_0 += 1)
							{
								// carray: (0) => (0) @ (1)
								for (int i_1 = 0; i_1 <= 0; i_1 += 1)
								{
									// sub                    : i_0 i_1
									// ori_name               : aesl_tmp_3[i_0].data
									// sub_1st_elem           : 0 0
									// ori_name_1st_elem      : aesl_tmp_3[0].data
									// output_left_conversion : aesl_tmp_3[i_0].data
									// output_type_conversion : (out_V_data_V_lv0_0_0_1_lv1_0_0_1[hls_map_index]).to_string(SC_BIN).c_str()
									if (&(aesl_tmp_3[0].data) != NULL) // check the null address if the c port is array or others
									{
										aesl_tmp_3[i_0].data = (out_V_data_V_lv0_0_0_1_lv1_0_0_1[hls_map_index]).to_string(SC_BIN).c_str();
										hls_map_index++;
									}
								}
							}
						}
					}
				}
			}
		}

		// output port post check: "out_V_last"
		aesl_fh.read(AUTOTB_TVOUT_PC_out_V_last, AESL_token); // [[transaction]]
		if (AESL_token != "[[transaction]]")
		{
			exit(1);
		}
		aesl_fh.read(AUTOTB_TVOUT_PC_out_V_last, AESL_num); // transaction number

		if (atoi(AESL_num.c_str()) == AESL_transaction_pc)
		{
			aesl_fh.read(AUTOTB_TVOUT_PC_out_V_last, AESL_token); // data

			std::vector<sc_bv<1> > out_V_last_pc_buffer;
			int i = 0;

			while (AESL_token != "[[/transaction]]")
			{
				bool no_x = false;
				bool err = false;

				// search and replace 'X' with "0" from the 1st char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('X');
					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "WARNING: [SIM 212-201] RTL produces unknown value 'X' on port 'out_V_last', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				no_x = false;

				// search and replace 'x' with "0" from the 3rd char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('x', 2);

					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "WARNING: [SIM 212-201] RTL produces unknown value 'X' on port 'out_V_last', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				// push token into output port buffer
				if (AESL_token != "")
				{
					out_V_last_pc_buffer.push_back(AESL_token.c_str());
					i++;
				}

				aesl_fh.read(AUTOTB_TVOUT_PC_out_V_last, AESL_token); // data or [[/transaction]]

				if (AESL_token == "[[[/runtime]]]" || aesl_fh.eof(AUTOTB_TVOUT_PC_out_V_last))
				{
					exit(1);
				}
			}

			// correct the buffer size the current transaction
			if (i != aesl_tmp_4)
			{
				aesl_tmp_4 = i;
			}

			if (aesl_tmp_4 > 0 && aesl_tmp_3.size() < aesl_tmp_4)
			{
				int aesl_tmp_3_size = aesl_tmp_3.size();

				for (int tmp_aesl_tmp_3 = 0; tmp_aesl_tmp_3 < aesl_tmp_4 - aesl_tmp_3_size; tmp_aesl_tmp_3++)
				{
					dtype_stream tmp;
					aesl_tmp_3.push_back(tmp);
				}
			}

			// ***********************************
			if (i > 0)
			{
				// RTL Name: out_V_last
				{
					// bitslice(0, 0)
					// {
						// celement: out.V.last(0, 0)
						// {
							sc_lv<1>* out_V_last_lv0_0_0_1_lv1_0_0_1 = new sc_lv<1>[aesl_tmp_4 - aesl_tmp_5];
						// }
					// }

					// bitslice(0, 0)
					{
						int hls_map_index = 0;
						// celement: out.V.last(0, 0)
						{
							// carray: (aesl_tmp_5) => (aesl_tmp_4 - 1) @ (1)
							for (int i_0 = aesl_tmp_5; i_0 <= aesl_tmp_4 - 1; i_0 += 1)
							{
								// carray: (0) => (0) @ (1)
								for (int i_1 = 0; i_1 <= 0; i_1 += 1)
								{
									if (&(aesl_tmp_3[0].last) != NULL) // check the null address if the c port is array or others
									{
										out_V_last_lv0_0_0_1_lv1_0_0_1[hls_map_index].range(0, 0) = sc_bv<1>(out_V_last_pc_buffer[hls_map_index].range(0, 0));
										hls_map_index++;
									}
								}
							}
						}
					}

					// bitslice(0, 0)
					{
						int hls_map_index = 0;
						// celement: out.V.last(0, 0)
						{
							// carray: (aesl_tmp_5) => (aesl_tmp_4 - 1) @ (1)
							for (int i_0 = aesl_tmp_5; i_0 <= aesl_tmp_4 - 1; i_0 += 1)
							{
								// carray: (0) => (0) @ (1)
								for (int i_1 = 0; i_1 <= 0; i_1 += 1)
								{
									// sub                    : i_0 i_1
									// ori_name               : aesl_tmp_3[i_0].last
									// sub_1st_elem           : 0 0
									// ori_name_1st_elem      : aesl_tmp_3[0].last
									// output_left_conversion : aesl_tmp_3[i_0].last
									// output_type_conversion : (out_V_last_lv0_0_0_1_lv1_0_0_1[hls_map_index]).to_uint64()
									if (&(aesl_tmp_3[0].last) != NULL) // check the null address if the c port is array or others
									{
										aesl_tmp_3[i_0].last = (out_V_last_lv0_0_0_1_lv1_0_0_1[hls_map_index]).to_uint64();
										hls_map_index++;
									}
								}
							}
						}
					}
				}
			}
		}

		// push back output stream: "out"
		for (int i = 0; i < aesl_tmp_4; i++)
		{
			out.write(aesl_tmp_3[i]);
		}

		AESL_transaction_pc++;
	}
	else
	{
		CodeState = ENTER_WRAPC;
		static unsigned AESL_transaction;

		static AESL_FILE_HANDLER aesl_fh;

		// "in_V_V"
		char* tvin_in_V_V = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_in_V_V);
		char* wrapc_stream_size_in_in_V_V = new char[50];
		aesl_fh.touch(WRAPC_STREAM_SIZE_IN_in_V_V);
		char* wrapc_stream_ingress_status_in_V_V = new char[50];
		aesl_fh.touch(WRAPC_STREAM_INGRESS_STATUS_in_V_V);

		// "out_V_data_V"
		char* tvin_out_V_data_V = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_out_V_data_V);
		char* tvout_out_V_data_V = new char[50];
		aesl_fh.touch(AUTOTB_TVOUT_out_V_data_V);
		char* wrapc_stream_size_out_out_V_data_V = new char[50];
		aesl_fh.touch(WRAPC_STREAM_SIZE_OUT_out_V_data_V);
		char* wrapc_stream_egress_status_out_V_data_V = new char[50];
		aesl_fh.touch(WRAPC_STREAM_EGRESS_STATUS_out_V_data_V);

		// "out_V_last"
		char* tvin_out_V_last = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_out_V_last);
		char* tvout_out_V_last = new char[50];
		aesl_fh.touch(AUTOTB_TVOUT_out_V_last);
		char* wrapc_stream_size_out_out_V_last = new char[50];
		aesl_fh.touch(WRAPC_STREAM_SIZE_OUT_out_V_last);
		char* wrapc_stream_egress_status_out_V_last = new char[50];
		aesl_fh.touch(WRAPC_STREAM_EGRESS_STATUS_out_V_last);

		// "ch_div_K"
		char* tvin_ch_div_K = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_ch_div_K);

		// "height_in"
		char* tvin_height_in = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_height_in);

		// "width_in"
		char* tvin_width_in = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_width_in);

		// "height_out"
		char* tvin_height_out = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_height_out);

		// "width_out"
		char* tvin_width_out = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_width_out);

		// "Kx"
		char* tvin_Kx = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_Kx);

		// "Ky"
		char* tvin_Ky = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_Ky);

		CodeState = DUMP_INPUTS;
		static INTER_TCL_FILE tcl_file(INTER_TCL);
		int leading_zero;

		// dump stream tvin: "in"
		std::vector<ap_int<128> > aesl_tmp_0;
		int aesl_tmp_1 = 0;
		while (!in.empty())
		{
			aesl_tmp_0.push_back(in.read());
			aesl_tmp_1++;
		}

		// dump stream tvin: "out"
		std::vector<dtype_stream > aesl_tmp_3;
		int aesl_tmp_4 = 0;
		while (!out.empty())
		{
			aesl_tmp_3.push_back(out.read());
			aesl_tmp_4++;
		}

		// [[transaction]]
		sprintf(tvin_ch_div_K, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVIN_ch_div_K, tvin_ch_div_K);

		sc_bv<32> ch_div_K_tvin_wrapc_buffer;

		// RTL Name: ch_div_K
		{
			// bitslice(31, 0)
			{
				// celement: ch_div_K(31, 0)
				{
					// carray: (0) => (0) @ (0)
					{
						// sub                   : 
						// ori_name              : ch_div_K
						// sub_1st_elem          : 
						// ori_name_1st_elem     : ch_div_K
						// regulate_c_name       : ch_div_K
						// input_type_conversion : ch_div_K
						if (&(ch_div_K) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<32> ch_div_K_tmp_mem;
							ch_div_K_tmp_mem = ch_div_K;
							ch_div_K_tvin_wrapc_buffer.range(31, 0) = ch_div_K_tmp_mem.range(31, 0);
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 1; i++)
		{
			sprintf(tvin_ch_div_K, "%s\n", (ch_div_K_tvin_wrapc_buffer).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVIN_ch_div_K, tvin_ch_div_K);
		}

		tcl_file.set_num(1, &tcl_file.ch_div_K_depth);
		sprintf(tvin_ch_div_K, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVIN_ch_div_K, tvin_ch_div_K);

		// [[transaction]]
		sprintf(tvin_height_in, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVIN_height_in, tvin_height_in);

		sc_bv<32> height_in_tvin_wrapc_buffer;

		// RTL Name: height_in
		{
			// bitslice(31, 0)
			{
				// celement: height_in(31, 0)
				{
					// carray: (0) => (0) @ (0)
					{
						// sub                   : 
						// ori_name              : height_in
						// sub_1st_elem          : 
						// ori_name_1st_elem     : height_in
						// regulate_c_name       : height_in
						// input_type_conversion : height_in
						if (&(height_in) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<32> height_in_tmp_mem;
							height_in_tmp_mem = height_in;
							height_in_tvin_wrapc_buffer.range(31, 0) = height_in_tmp_mem.range(31, 0);
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 1; i++)
		{
			sprintf(tvin_height_in, "%s\n", (height_in_tvin_wrapc_buffer).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVIN_height_in, tvin_height_in);
		}

		tcl_file.set_num(1, &tcl_file.height_in_depth);
		sprintf(tvin_height_in, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVIN_height_in, tvin_height_in);

		// [[transaction]]
		sprintf(tvin_width_in, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVIN_width_in, tvin_width_in);

		sc_bv<32> width_in_tvin_wrapc_buffer;

		// RTL Name: width_in
		{
			// bitslice(31, 0)
			{
				// celement: width_in(31, 0)
				{
					// carray: (0) => (0) @ (0)
					{
						// sub                   : 
						// ori_name              : width_in
						// sub_1st_elem          : 
						// ori_name_1st_elem     : width_in
						// regulate_c_name       : width_in
						// input_type_conversion : width_in
						if (&(width_in) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<32> width_in_tmp_mem;
							width_in_tmp_mem = width_in;
							width_in_tvin_wrapc_buffer.range(31, 0) = width_in_tmp_mem.range(31, 0);
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 1; i++)
		{
			sprintf(tvin_width_in, "%s\n", (width_in_tvin_wrapc_buffer).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVIN_width_in, tvin_width_in);
		}

		tcl_file.set_num(1, &tcl_file.width_in_depth);
		sprintf(tvin_width_in, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVIN_width_in, tvin_width_in);

		// [[transaction]]
		sprintf(tvin_height_out, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVIN_height_out, tvin_height_out);

		sc_bv<32> height_out_tvin_wrapc_buffer;

		// RTL Name: height_out
		{
			// bitslice(31, 0)
			{
				// celement: height_out(31, 0)
				{
					// carray: (0) => (0) @ (0)
					{
						// sub                   : 
						// ori_name              : height_out
						// sub_1st_elem          : 
						// ori_name_1st_elem     : height_out
						// regulate_c_name       : height_out
						// input_type_conversion : height_out
						if (&(height_out) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<32> height_out_tmp_mem;
							height_out_tmp_mem = height_out;
							height_out_tvin_wrapc_buffer.range(31, 0) = height_out_tmp_mem.range(31, 0);
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 1; i++)
		{
			sprintf(tvin_height_out, "%s\n", (height_out_tvin_wrapc_buffer).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVIN_height_out, tvin_height_out);
		}

		tcl_file.set_num(1, &tcl_file.height_out_depth);
		sprintf(tvin_height_out, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVIN_height_out, tvin_height_out);

		// [[transaction]]
		sprintf(tvin_width_out, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVIN_width_out, tvin_width_out);

		sc_bv<32> width_out_tvin_wrapc_buffer;

		// RTL Name: width_out
		{
			// bitslice(31, 0)
			{
				// celement: width_out(31, 0)
				{
					// carray: (0) => (0) @ (0)
					{
						// sub                   : 
						// ori_name              : width_out
						// sub_1st_elem          : 
						// ori_name_1st_elem     : width_out
						// regulate_c_name       : width_out
						// input_type_conversion : width_out
						if (&(width_out) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<32> width_out_tmp_mem;
							width_out_tmp_mem = width_out;
							width_out_tvin_wrapc_buffer.range(31, 0) = width_out_tmp_mem.range(31, 0);
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 1; i++)
		{
			sprintf(tvin_width_out, "%s\n", (width_out_tvin_wrapc_buffer).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVIN_width_out, tvin_width_out);
		}

		tcl_file.set_num(1, &tcl_file.width_out_depth);
		sprintf(tvin_width_out, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVIN_width_out, tvin_width_out);

		// [[transaction]]
		sprintf(tvin_Kx, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVIN_Kx, tvin_Kx);

		sc_bv<32> Kx_tvin_wrapc_buffer;

		// RTL Name: Kx
		{
			// bitslice(31, 0)
			{
				// celement: Kx(31, 0)
				{
					// carray: (0) => (0) @ (0)
					{
						// sub                   : 
						// ori_name              : Kx
						// sub_1st_elem          : 
						// ori_name_1st_elem     : Kx
						// regulate_c_name       : Kx
						// input_type_conversion : Kx
						if (&(Kx) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<32> Kx_tmp_mem;
							Kx_tmp_mem = Kx;
							Kx_tvin_wrapc_buffer.range(31, 0) = Kx_tmp_mem.range(31, 0);
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 1; i++)
		{
			sprintf(tvin_Kx, "%s\n", (Kx_tvin_wrapc_buffer).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVIN_Kx, tvin_Kx);
		}

		tcl_file.set_num(1, &tcl_file.Kx_depth);
		sprintf(tvin_Kx, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVIN_Kx, tvin_Kx);

		// [[transaction]]
		sprintf(tvin_Ky, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVIN_Ky, tvin_Ky);

		sc_bv<32> Ky_tvin_wrapc_buffer;

		// RTL Name: Ky
		{
			// bitslice(31, 0)
			{
				// celement: Ky(31, 0)
				{
					// carray: (0) => (0) @ (0)
					{
						// sub                   : 
						// ori_name              : Ky
						// sub_1st_elem          : 
						// ori_name_1st_elem     : Ky
						// regulate_c_name       : Ky
						// input_type_conversion : Ky
						if (&(Ky) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<32> Ky_tmp_mem;
							Ky_tmp_mem = Ky;
							Ky_tvin_wrapc_buffer.range(31, 0) = Ky_tmp_mem.range(31, 0);
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 1; i++)
		{
			sprintf(tvin_Ky, "%s\n", (Ky_tvin_wrapc_buffer).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVIN_Ky, tvin_Ky);
		}

		tcl_file.set_num(1, &tcl_file.Ky_depth);
		sprintf(tvin_Ky, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVIN_Ky, tvin_Ky);

		// push back input stream: "in"
		for (int i = 0; i < aesl_tmp_1; i++)
		{
			in.write(aesl_tmp_0[i]);
		}

		// push back input stream: "out"
		for (int i = 0; i < aesl_tmp_4; i++)
		{
			out.write(aesl_tmp_3[i]);
		}

// [call_c_dut] ---------->

		CodeState = CALL_C_DUT;
		pool(in, out, ch_div_K, height_in, width_in, height_out, width_out, Kx, Ky);

		CodeState = DUMP_OUTPUTS;
		// record input size to tv3: "in"
		int aesl_tmp_2 = in.size();

		// pop output stream: "out"
		int aesl_tmp_5 = aesl_tmp_4;
		aesl_tmp_4 = 0;
     aesl_tmp_3.clear();
		while (!out.empty())
		{
			aesl_tmp_3.push_back(out.read());
			aesl_tmp_4++;
		}

		// [[transaction]]
		sprintf(tvin_in_V_V, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVIN_in_V_V, tvin_in_V_V);
		aesl_fh.write(WRAPC_STREAM_INGRESS_STATUS_in_V_V, tvin_in_V_V);

		sc_bv<128>* in_V_V_tvin_wrapc_buffer = new sc_bv<128>[aesl_tmp_1 - aesl_tmp_2];

		// RTL Name: in_V_V
		{
			// bitslice(127, 0)
			{
				int hls_map_index = 0;
				// celement: in.V.V(127, 0)
				{
					// carray: (0) => (aesl_tmp_1 - aesl_tmp_2 - 1) @ (1)
					for (int i_0 = 0; i_0 <= aesl_tmp_1 - aesl_tmp_2 - 1; i_0 += 1)
					{
						// sub                   : i_0
						// ori_name              : aesl_tmp_0[i_0]
						// sub_1st_elem          : 0
						// ori_name_1st_elem     : aesl_tmp_0[0]
						// regulate_c_name       : in_V_V
						// input_type_conversion : (aesl_tmp_0[i_0]).to_string(2).c_str()
						if (&(aesl_tmp_0[0]) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<128> in_V_V_tmp_mem;
							in_V_V_tmp_mem = (aesl_tmp_0[i_0]).to_string(2).c_str();
							in_V_V_tvin_wrapc_buffer[hls_map_index].range(127, 0) = in_V_V_tmp_mem.range(127, 0);
                                 	       hls_map_index++;
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < aesl_tmp_1 - aesl_tmp_2; i++)
		{
			sprintf(tvin_in_V_V, "%s\n", (in_V_V_tvin_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVIN_in_V_V, tvin_in_V_V);
		}

		// dump stream ingress status to file
		sc_int<32> stream_ingress_size_in_V_V = aesl_tmp_1;
		aesl_fh.write(WRAPC_STREAM_INGRESS_STATUS_in_V_V, stream_ingress_size_in_V_V.to_string().c_str());
		aesl_fh.write(WRAPC_STREAM_INGRESS_STATUS_in_V_V, "\n");

		for (int i = 0; i < aesl_tmp_1 - aesl_tmp_2; i++)
		{
			stream_ingress_size_in_V_V--;
			aesl_fh.write(WRAPC_STREAM_INGRESS_STATUS_in_V_V, stream_ingress_size_in_V_V.to_string().c_str());
			aesl_fh.write(WRAPC_STREAM_INGRESS_STATUS_in_V_V, "\n");
		}

		tcl_file.set_num(aesl_tmp_1 - aesl_tmp_2, &tcl_file.in_V_V_depth);
		sprintf(tvin_in_V_V, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVIN_in_V_V, tvin_in_V_V);
		aesl_fh.write(WRAPC_STREAM_INGRESS_STATUS_in_V_V, tvin_in_V_V);

		// release memory allocation
		delete [] in_V_V_tvin_wrapc_buffer;

		// dump stream size
		sprintf(wrapc_stream_size_in_in_V_V, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(WRAPC_STREAM_SIZE_IN_in_V_V, wrapc_stream_size_in_in_V_V);
		sprintf(wrapc_stream_size_in_in_V_V, "%d\n", aesl_tmp_1 - aesl_tmp_2);
		aesl_fh.write(WRAPC_STREAM_SIZE_IN_in_V_V, wrapc_stream_size_in_in_V_V);
		sprintf(wrapc_stream_size_in_in_V_V, "[[/transaction]] \n");
		aesl_fh.write(WRAPC_STREAM_SIZE_IN_in_V_V, wrapc_stream_size_in_in_V_V);

		// [[transaction]]
		sprintf(tvout_out_V_data_V, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVOUT_out_V_data_V, tvout_out_V_data_V);

		sc_bv<128>* out_V_data_V_tvout_wrapc_buffer = new sc_bv<128>[aesl_tmp_4 - aesl_tmp_5];

		// RTL Name: out_V_data_V
		{
			// bitslice(127, 0)
			{
				int hls_map_index = 0;
				// celement: out.V.data.V(127, 0)
				{
					// carray: (aesl_tmp_5) => (aesl_tmp_4 - 1) @ (1)
					for (int i_0 = aesl_tmp_5; i_0 <= aesl_tmp_4 - 1; i_0 += 1)
					{
						// carray: (0) => (0) @ (1)
						for (int i_1 = 0; i_1 <= 0; i_1 += 1)
						{
							// sub                   : i_0 i_1
							// ori_name              : aesl_tmp_3[i_0].data
							// sub_1st_elem          : 0 0
							// ori_name_1st_elem     : aesl_tmp_3[0].data
							// regulate_c_name       : out_V_data_V
							// input_type_conversion : (aesl_tmp_3[i_0].data).to_string(2).c_str()
							if (&(aesl_tmp_3[0].data) != NULL) // check the null address if the c port is array or others
							{
								sc_lv<128> out_V_data_V_tmp_mem;
								out_V_data_V_tmp_mem = (aesl_tmp_3[i_0].data).to_string(2).c_str();
								out_V_data_V_tvout_wrapc_buffer[hls_map_index].range(127, 0) = out_V_data_V_tmp_mem.range(127, 0);
                                 		       hls_map_index++;
							}
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < aesl_tmp_4 - aesl_tmp_5; i++)
		{
			sprintf(tvout_out_V_data_V, "%s\n", (out_V_data_V_tvout_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVOUT_out_V_data_V, tvout_out_V_data_V);
		}

		tcl_file.set_num(aesl_tmp_4 - aesl_tmp_5, &tcl_file.out_V_data_V_depth);
		sprintf(tvout_out_V_data_V, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVOUT_out_V_data_V, tvout_out_V_data_V);

		// release memory allocation
		delete [] out_V_data_V_tvout_wrapc_buffer;

		// dump stream size
		sprintf(wrapc_stream_size_out_out_V_data_V, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(WRAPC_STREAM_SIZE_OUT_out_V_data_V, wrapc_stream_size_out_out_V_data_V);
		sprintf(wrapc_stream_size_out_out_V_data_V, "%d\n", aesl_tmp_4 - aesl_tmp_5);
		aesl_fh.write(WRAPC_STREAM_SIZE_OUT_out_V_data_V, wrapc_stream_size_out_out_V_data_V);
		sprintf(wrapc_stream_size_out_out_V_data_V, "[[/transaction]] \n");
		aesl_fh.write(WRAPC_STREAM_SIZE_OUT_out_V_data_V, wrapc_stream_size_out_out_V_data_V);

		// [[transaction]]
		sprintf(tvout_out_V_last, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVOUT_out_V_last, tvout_out_V_last);

		sc_bv<1>* out_V_last_tvout_wrapc_buffer = new sc_bv<1>[aesl_tmp_4 - aesl_tmp_5];

		// RTL Name: out_V_last
		{
			// bitslice(0, 0)
			{
				int hls_map_index = 0;
				// celement: out.V.last(0, 0)
				{
					// carray: (aesl_tmp_5) => (aesl_tmp_4 - 1) @ (1)
					for (int i_0 = aesl_tmp_5; i_0 <= aesl_tmp_4 - 1; i_0 += 1)
					{
						// carray: (0) => (0) @ (1)
						for (int i_1 = 0; i_1 <= 0; i_1 += 1)
						{
							// sub                   : i_0 i_1
							// ori_name              : aesl_tmp_3[i_0].last
							// sub_1st_elem          : 0 0
							// ori_name_1st_elem     : aesl_tmp_3[0].last
							// regulate_c_name       : out_V_last
							// input_type_conversion : aesl_tmp_3[i_0].last
							if (&(aesl_tmp_3[0].last) != NULL) // check the null address if the c port is array or others
							{
								sc_lv<1> out_V_last_tmp_mem;
								out_V_last_tmp_mem = aesl_tmp_3[i_0].last;
								out_V_last_tvout_wrapc_buffer[hls_map_index].range(0, 0) = out_V_last_tmp_mem.range(0, 0);
                                 		       hls_map_index++;
							}
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < aesl_tmp_4 - aesl_tmp_5; i++)
		{
			sprintf(tvout_out_V_last, "%s\n", (out_V_last_tvout_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVOUT_out_V_last, tvout_out_V_last);
		}

		tcl_file.set_num(aesl_tmp_4 - aesl_tmp_5, &tcl_file.out_V_last_depth);
		sprintf(tvout_out_V_last, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVOUT_out_V_last, tvout_out_V_last);

		// release memory allocation
		delete [] out_V_last_tvout_wrapc_buffer;

		// dump stream size
		sprintf(wrapc_stream_size_out_out_V_last, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(WRAPC_STREAM_SIZE_OUT_out_V_last, wrapc_stream_size_out_out_V_last);
		sprintf(wrapc_stream_size_out_out_V_last, "%d\n", aesl_tmp_4 - aesl_tmp_5);
		aesl_fh.write(WRAPC_STREAM_SIZE_OUT_out_V_last, wrapc_stream_size_out_out_V_last);
		sprintf(wrapc_stream_size_out_out_V_last, "[[/transaction]] \n");
		aesl_fh.write(WRAPC_STREAM_SIZE_OUT_out_V_last, wrapc_stream_size_out_out_V_last);

		// push back output stream: "out"
		for (int i = 0; i < aesl_tmp_4; i++)
		{
			out.write(aesl_tmp_3[i]);
		}

		CodeState = DELETE_CHAR_BUFFERS;
		// release memory allocation: "in_V_V"
		delete [] tvin_in_V_V;
		delete [] wrapc_stream_size_in_in_V_V;
		// release memory allocation: "out_V_data_V"
		delete [] tvout_out_V_data_V;
		delete [] tvin_out_V_data_V;
		delete [] wrapc_stream_size_out_out_V_data_V;
		// release memory allocation: "out_V_last"
		delete [] tvout_out_V_last;
		delete [] tvin_out_V_last;
		delete [] wrapc_stream_size_out_out_V_last;
		// release memory allocation: "ch_div_K"
		delete [] tvin_ch_div_K;
		// release memory allocation: "height_in"
		delete [] tvin_height_in;
		// release memory allocation: "width_in"
		delete [] tvin_width_in;
		// release memory allocation: "height_out"
		delete [] tvin_height_out;
		// release memory allocation: "width_out"
		delete [] tvin_width_out;
		// release memory allocation: "Kx"
		delete [] tvin_Kx;
		// release memory allocation: "Ky"
		delete [] tvin_Ky;

		AESL_transaction++;

		tcl_file.set_num(AESL_transaction , &tcl_file.trans_num);
	}
}

